// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const BankWithTick = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <g id="Layer_2" data-name="Layer 2">
                        <line
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            x1="18"
                            y1="13"
                            x2="18"
                            y2="20"
                        />
                        <polygon
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            points="3 13 21 13 12 8 3 13"
                        />
                        <line
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            x1="21"
                            y1="21"
                            x2="3"
                            y2="21"
                        />
                        <polyline
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            points="3 6 5 8 10 3"
                        />
                        <line
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            x1="10"
                            y1="13"
                            x2="10"
                            y2="20"
                        />
                        <line
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            x1="6"
                            y1="13"
                            x2="6"
                            y2="20"
                        />
                        <line
                            strokeWidth="2"
                            fill="none"
                            className="stroke"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            x1="14"
                            y1="13"
                            x2="14"
                            y2="20"
                        />
                    </g>
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

BankWithTick.displayName = "BankWithTick";

export default BankWithTick;
