// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const Braces = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15,4h1a2,2,0,0,1,2,2V9a3,3,0,0,0,3,3h0a3,3,0,0,0-3,3v3a2,2,0,0,1-2,2H15"
                    />
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M9,4H8A2,2,0,0,0,6,6V9a3,3,0,0,1-3,3H3a3,3,0,0,1,3,3v3a2,2,0,0,0,2,2H9"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

Braces.displayName = "Braces";

export default Braces;
