// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const CalendarLineIcon = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <rect
                        x="3"
                        y="5"
                        width="18"
                        height="16"
                        className="stroke"
                        strokeWidth="2"
                        strokeLinejoin="round"
                    />
                    <path d="M3 10H21" className="stroke" strokeWidth="2" />
                    <path
                        d="M5.99999 3L6 6M18 3L18 6M9.99999 3L10 6M14 3L14 6"
                        className="stroke"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

CalendarLineIcon.displayName = "CalendarLineIcon";

export default CalendarLineIcon;
