// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const Gear = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <circle
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        cx="12"
                        cy="12"
                        r="2.5"
                    />
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M18.5,12a5.77,5.77,0,0,0-.09-1l2.38-1.75-2-3.46L16.09,7a6.4,6.4,0,0,0-1.76-1L14,3H10L9.67,5.94A6.4,6.4,0,0,0,7.91,7L5.21,5.77l-2,3.46L5.59,11a5.83,5.83,0,0,0,0,2L3.21,14.77l2,3.46,2.7-1.18a6.4,6.4,0,0,0,1.76,1L10,21h4l.33-2.94a6.4,6.4,0,0,0,1.76-1l2.7,1.18,2-3.46L18.41,13A5.77,5.77,0,0,0,18.5,12Z"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

Gear.displayName = "Gear";

export default Gear;
