// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const HospitalSign = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M20,9H15V4a1,1,0,0,0-1-1H10A1,1,0,0,0,9,4V9H4a1,1,0,0,0-1,1v4a1,1,0,0,0,1,1H9v5a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V15h5a1,1,0,0,0,1-1V10A1,1,0,0,0,20,9Z"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

HospitalSign.displayName = "HospitalSign";

export default HospitalSign;
