// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const MobileWithBraces = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15,18v2a1,1,0,0,1-1,1H4a1,1,0,0,1-1-1V4A1,1,0,0,1,4,3H14a1,1,0,0,1,1,1V5"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="8"
                        y1="17"
                        x2="10"
                        y2="17"
                    />
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M18,8h.43a.88.88,0,0,1,.86.9v1.35a1.32,1.32,0,0,0,1.28,1.35h0A1.32,1.32,0,0,0,19.29,13V14.3a.88.88,0,0,1-.86.9H18"
                    />
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15,8h-.43a.88.88,0,0,0-.86.9v1.35a1.32,1.32,0,0,1-1.28,1.35h0A1.32,1.32,0,0,1,13.71,13V14.3a.88.88,0,0,0,.86.9H15"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

MobileWithBraces.displayName = "MobileWithBraces";

export default MobileWithBraces;
