// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const Passbook = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M3.81063 12.7575C3.92193 12.3123 4.32191 12 4.78078 12H19.2192C19.6781 12 20.0781 12.3123 20.1894 12.7575L21.3787 17.5149C21.6943 18.7772 20.7396 20 19.4384 20H4.56155C3.26041 20 2.30569 18.7772 2.62127 17.5149L3.81063 12.7575Z"
                        className="stroke"
                        strokeWidth="2"
                    />
                    <path
                        d="M20 11C20 11.5523 19.5523 12 19 12L5 12C4.44772 12 4 11.5523 4 11L4 6C4 4.89543 4.89543 4 6 4L18 4C19.1046 4 20 4.89543 20 6L20 11Z"
                        className="stroke"
                        strokeWidth="2"
                    />
                    <path
                        d="M11 16L17 16"
                        className="stroke"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />
                    <path
                        d="M11 8L17 8"
                        className="stroke"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />
                    <path
                        d="M7 16L8 16"
                        className="stroke"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />
                    <path
                        d="M7 8L8 8"
                        className="stroke"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

Passbook.displayName = "Passbook";

export default Passbook;
