// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const PencilWithSign = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M3,20.16c2.27-1.48,3.39-2.59,4-2,.84.82-.78,2.26,0,3,.45.43,2,0,4-1"
                    />
                    <rect
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x="14.12"
                        y="3.53"
                        width="5.25"
                        height="11.38"
                        transform="translate(3.66 -4.72) rotate(17.97)"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="18.5"
                        y1="3.81"
                        x2="14.99"
                        y2="14.64"
                    />
                    <polyline
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        points="17.49 15.45 13.64 18.8 12.49 13.83"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

PencilWithSign.displayName = "PencilWithSign";

export default PencilWithSign;
