// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const RupeeWithLoadingArrows = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M3.51,9A9.18,9.18,0,0,1,5.29,6,9,9,0,0,1,21,12"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="16"
                        y1="7"
                        x2="8"
                        y2="7"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="8"
                        y1="10"
                        x2="16"
                        y2="10"
                    />
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M10.5,7a2.94,2.94,0,0,1,3,3c-.1,1.7-1.5,4-5.5,3l6,5"
                    />
                    <polyline
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        points="2.96 7.62 2.98 9.78 5.04 9.13"
                    />
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M20.06,16a9.05,9.05,0,0,1-.59,1A9.25,9.25,0,0,1,12,21a8.9,8.9,0,0,1-8.78-7"
                    />
                    <polyline
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        points="21 17.38 20.98 15.22 18.91 15.87"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

RupeeWithLoadingArrows.displayName = "RupeeWithLoadingArrows";

export default RupeeWithLoadingArrows;
