// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const Spanner = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        fill="none"
                        className="stroke"
                        strokeWidth="2"
                        d="M2.5,25.74l6.08-6.07A8,8,0,0,0,17.35,18a8.11,8.11,0,0,0,2.13-7.78l-5.66,5.66L9.58,14.42,8.16,10.18l5.66-5.66A8.11,8.11,0,0,0,6,6.65a8,8,0,0,0-1.71,8.77L-1.74,21.5"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

Spanner.displayName = "Spanner";

export default Spanner;
