// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const StoveWithFlame = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    id="Layer_1"
                    data-name="Layer 1"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                >
                    <defs></defs>
                    <path
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M18.3,16.14a7.79,7.79,0,0,0-1-8.08l-3.2,3s-4-4-3.15-8.08S2.49,10.08,5.65,16.14"
                    />
                    <rect
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x="3"
                        y="17"
                        width="18"
                        height="5"
                        rx="2"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="9"
                        y1="19.5"
                        x2="9"
                        y2="19.5"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="12"
                        y1="19.5"
                        x2="12"
                        y2="19.5"
                    />
                    <line
                        strokeWidth="2"
                        fill="none"
                        className="stroke"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        x1="15"
                        y1="19.5"
                        x2="15"
                        y2="19.5"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

StoveWithFlame.displayName = "StoveWithFlame";

export default StoveWithFlame;
