// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const ThreeSliders = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return <SVGLineIconWrapper {...props}></SVGLineIconWrapper>;
    }
);

ThreeSliders.displayName = "ThreeSliders";

export default ThreeSliders;
