// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const TwoRectangles = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <rect x="9" y="7" width="10" height="14" rx="1" className="stroke" strokeWidth="2" />
                    <path
                        d="M16 6.5V4C16 3.44772 15.5523 3 15 3H6C5.44772 3 5 3.44772 5 4L5 16C5 16.5523 5.44772 17 6 17H6.375H8"
                        className="stroke"
                        strokeWidth="2"
                    />
                </svg>
            </SVGLineIconWrapper>
        );
    }
);

TwoRectangles.displayName = "TwoRectangles";

export default TwoRectangles;
