const getReactPictogramTemplate = (fileName, svgContent) => {
    return `// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const ${fileName} = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.${fileName}} {...props}  >
                ${svgContent}
            </SVGPictogramWrapper>
        );
    }
);

${fileName}.displayName = '${fileName}';


export default ${fileName};`;
};

const getReactLineIconTemplate = (fileName, svgContent) => {
    return `// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LineIconProps } from "../../types";
import { SVGLineIconWrapper } from "../../styles";

export const ${fileName} = React.forwardRef<SVGSVGElement, LineIconProps>(
    ({ width = 24, height = 24, ...props }, forwardedRef) => {
        return (
            <SVGLineIconWrapper {...props} >
                ${svgContent}
            </SVGLineIconWrapper>
        );
    }
);

${fileName}.displayName = '${fileName}';

export default ${fileName};`;
};

const getReactLogoTemplate = (fileName, svgContent) => {
    return `// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { LogoProps } from "../../types";
import { SVGLogoWrapper } from "../../styles";

export const ${fileName} = React.forwardRef<SVGSVGElement, LogoProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGLogoWrapper {...props} >
                ${svgContent}
            </SVGLogoWrapper>
        );
    }
);

${fileName}.displayName = '${fileName}';

export default ${fileName};`;
};

module.exports = {
    getReactPictogramTemplate,
    getReactLineIconTemplate,
    getReactLogoTemplate,
};
