// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const BankWithExclamation = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.BankWithExclamation} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path d="M15 32.571H9V48.571H15V32.571Z" fill="white" />
                    <path d="M28 32.571H22V48.571H28V32.571Z" fill="white" />
                    <path d="M42 32.571H36V48.571H42V32.571Z" fill="white" />
                    <path d="M55 32.571H49V48.571H55V32.571Z" fill="white" />
                    <path
                        d="M58 48.5708H6C4.89543 48.5708 4 49.4662 4 50.5708V54.5708C4 55.6754 4.89543 56.5708 6 56.5708H58C59.1046 56.5708 60 55.6754 60 54.5708V50.5708C60 49.4662 59.1046 48.5708 58 48.5708Z"
                        className="base"
                    />
                    <path
                        d="M58 32.5708H6C5.46957 32.5708 4.96086 32.3601 4.58579 31.985C4.21071 31.6099 4 31.1012 4 30.5708V27.5708C3.99988 27.2518 4.07606 26.9374 4.22219 26.6538C4.36831 26.3703 4.58014 26.1258 4.84 25.9408L30.84 7.37077C31.1787 7.1296 31.5842 7 32 7C32.4158 7 32.8213 7.1296 33.16 7.37077L59.16 25.9408C59.4199 26.1258 59.6317 26.3703 59.7778 26.6538C59.9239 26.9374 60.0001 27.2518 60 27.5708V30.5708C60 31.1012 59.7893 31.6099 59.4142 31.985C59.0391 32.3601 58.5304 32.5708 58 32.5708Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path d="M15 29.571H9V51.571H15V29.571Z" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <path d="M28 29.571H22V51.571H28V29.571Z" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <path d="M42 29.571H36V51.571H42V29.571Z" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <path d="M55 29.571H49V51.571H55V29.571Z" className="base" />
                    </g>
                    <path
                        d="M52.5 62C57.7467 62 62 57.7467 62 52.5C62 47.2533 57.7467 43 52.5 43C47.2533 43 43 47.2533 43 52.5C43 57.7467 47.2533 62 52.5 62Z"
                        className="primary"
                    />
                    <circle cx="52.5" cy="58.5" r="1.5" className="secondary" />
                    <rect x="51" y="45" width="3" height="11" rx="1.5" className="secondary" />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

BankWithExclamation.displayName = "BankWithExclamation";

export default BankWithExclamation;
