// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const BarsWithExcalamationMark = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.BarsWithExcalamationMark} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <g className="mix-blend-multiply">
                        <path
                            d="M50.5 27C55.7467 27 60 22.7467 60 17.5C60 12.2533 55.7467 8 50.5 8C45.2533 8 41 12.2533 41 17.5C41 22.7467 45.2533 27 50.5 27Z"
                            fill="white"
                        />
                        <circle cx="50.5" cy="23.5" r="1.5" fill="white" />
                        <rect x="49" y="10" width="3" height="11" rx="1.5" fill="white" />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 41V55C4 55.5523 4.44772 56 5 56H11C11.5523 56 12 55.5523 12 55V41C12 40.4477 11.5523 40 11 40H5C4.44772 40 4 40.4477 4 41Z"
                            fill="white"
                        />
                        <path
                            d="M26 25V55C26 55.5523 26.4477 56 27 56H33C33.5523 56 34 55.5523 34 55V25C34 24.4477 33.5523 24 33 24H27C26.4477 24 26 24.4477 26 25Z"
                            fill="white"
                        />
                        <path
                            d="M15 33V55C15 55.5523 15.4477 56 16 56H22C22.5523 56 23 55.5523 23 55V33C23 32.4477 22.5523 32 22 32H16C15.4477 32 15 32.4477 15 33Z"
                            fill="white"
                        />
                        <path
                            d="M37 17V55C37 55.5523 37.4477 56 38 56H44C44.5523 56 45 55.5523 45 55V17C45 16.4477 44.5523 16 44 16H38C37.4477 16 37 16.4477 37 17Z"
                            fill="white"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M50.5 27C55.7467 27 60 22.7467 60 17.5C60 12.2533 55.7467 8 50.5 8C45.2533 8 41 12.2533 41 17.5C41 22.7467 45.2533 27 50.5 27Z"
                            className="primary"
                        />
                        <circle cx="50.5" cy="23.5" r="1.5" className="secondary" />
                        <rect x="49" y="10" width="3" height="11" rx="1.5" className="secondary" />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 41V55C4 55.5523 4.44772 56 5 56H11C11.5523 56 12 55.5523 12 55V41C12 40.4477 11.5523 40 11 40H5C4.44772 40 4 40.4477 4 41Z"
                            className="base"
                        />
                        <path
                            d="M26 25V55C26 55.5523 26.4477 56 27 56H33C33.5523 56 34 55.5523 34 55V25C34 24.4477 33.5523 24 33 24H27C26.4477 24 26 24.4477 26 25Z"
                            className="base"
                        />
                        <path
                            d="M15 33V55C15 55.5523 15.4477 56 16 56H22C22.5523 56 23 55.5523 23 55V33C23 32.4477 22.5523 32 22 32H16C15.4477 32 15 32.4477 15 33Z"
                            className="base"
                        />
                        <path
                            d="M37 17V55C37 55.5523 37.4477 56 38 56H44C44.5523 56 45 55.5523 45 55V17C45 16.4477 44.5523 16 44 16H38C37.4477 16 37 16.4477 37 17Z"
                            className="base"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

BarsWithExcalamationMark.displayName = "BarsWithExcalamationMark";

export default BarsWithExcalamationMark;
