// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const BookWithKarmaSymbol = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.BookWithKarmaSymbol} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g id="Layer_1" data-name="Layer 1">
                        <g clipPath="url(#clipPath)">
                            <path
                                className="base"
                                d="M56,62V10a2,2,0,0,0-2-2H10a2,2,0,0,0-2,2V62a2,2,0,0,0,2,2H54A2,2,0,0,0,56,62Z"
                            />
                            <path
                                className="secondary"
                                d="M40,8V.27c0-.27-.48-.37-.69-.15l-2,2.16a.46.46,0,0,1-.62,0l-2-2.16C34.48-.1,34,0,34,.27V8Z"
                            />
                            <path
                                className="tertiary"
                                d="M48,8V.27c0-.27-.48-.37-.69-.15l-2,2.16a.46.46,0,0,1-.62,0l-2-2.16C42.48-.1,42,0,42,.27V8Z"
                            />
                            <path
                                className="primary"
                                d="M54,8H52V59a1,1,0,0,1-1,1H8v2a2,2,0,0,0,2,2H54a2,2,0,0,0,2-2V10a2,2,0,0,0-2-2Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M30,48.75h-.42a4.91,4.91,0,0,1-4.1-3l-.19-.47,3.65-3.49-2.77-2.65L22.7,42.43A3.64,3.64,0,0,1,18.33,42a3.34,3.34,0,0,1-1-2.05,3.3,3.3,0,0,1,.54-2.22l.1-.13,3.29-3.13L17.81,31.1a3.35,3.35,0,0,1,.49-4.27,3.59,3.59,0,0,1,2.11-1,3.66,3.66,0,0,1,2.26.51l.14.09,3.33,3.19L28.91,27l-3.57-3.4.06-.39a4.75,4.75,0,0,1,5.05-3.94,4.67,4.67,0,0,1,2.75,1.26,4.61,4.61,0,0,1,1.4,2.69v.38L31.09,27l2.77,2.64,3.47-3.28a3.66,3.66,0,0,1,4.37.46,3.35,3.35,0,0,1,.49,4.27l-.1.13L38.8,34.37l3.39,3.26a3.29,3.29,0,0,1,.54,2.22,3.34,3.34,0,0,1-1,2,3.64,3.64,0,0,1-2.11,1,3.59,3.59,0,0,1-2.26-.49l-.13-.1-3.34-3.19-2.77,2.65,3.66,3.49-.2.47A5,5,0,0,1,30,48.75Zm-2.91-3.18a3.59,3.59,0,0,0,1.11,1.15,3.41,3.41,0,0,0,1.51.52A3.47,3.47,0,0,0,33,45.57l-3-2.81ZM38.2,41.12a2.13,2.13,0,0,0,2.5-.3,1.9,1.9,0,0,0,.55-1.09,1.86,1.86,0,0,0-.25-1.2l-3.28-3.12L35,38.05ZM19,38.53a1.8,1.8,0,0,0-.25,1.2,1.84,1.84,0,0,0,.57,1.09,2.13,2.13,0,0,0,2.5.3l3.23-3.07-2.77-2.64Zm8.22-.48L30,40.69l2.77-2.64L30,35.41Zm-3.86-3.68L26.14,37l2.77-2.64-2.77-2.65Zm7.72,0L33.86,37l2.77-2.64-2.77-2.65Zm3.85-3.68,2.77,2.64L41,30.21a1.86,1.86,0,0,0,.24-1.2,1.89,1.89,0,0,0-.56-1.09,2.15,2.15,0,0,0-2.5-.31ZM19,30.21l3.28,3.12,2.77-2.64-3.23-3.08a2.15,2.15,0,0,0-2.5.31A1.84,1.84,0,0,0,18.75,29,1.8,1.8,0,0,0,19,30.21Zm8.22.48L30,33.33l2.77-2.64L30,28ZM27,23.07,30,26l3-2.9a3.27,3.27,0,0,0-1-1.58,3.16,3.16,0,0,0-1.72-.73A3.23,3.23,0,0,0,27,23.07Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M21.5,24A1.5,1.5,0,1,0,20,22.5,1.5,1.5,0,0,0,21.5,24Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M38.5,24A1.5,1.5,0,1,0,37,22.5,1.5,1.5,0,0,0,38.5,24Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M21.5,47A1.5,1.5,0,1,0,20,45.5,1.5,1.5,0,0,0,21.5,47Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M38.5,47A1.5,1.5,0,1,0,37,45.5,1.5,1.5,0,0,0,38.5,47Z" />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

BookWithKarmaSymbol.displayName = "BookWithKarmaSymbol";

export default BookWithKarmaSymbol;
