// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const BoxWithRightArrow = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.BoxWithRightArrow} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <rect
                        x="60.4916"
                        y="34.2393"
                        width="21"
                        height="5"
                        rx="2.5"
                        transform="rotate(-180 60.4916 34.2393)"
                        fill="white"
                    />
                    <rect
                        x="45.4916"
                        y="41.2393"
                        width="13.3093"
                        height="4"
                        rx="2"
                        transform="rotate(-135 45.4916 41.2393)"
                        fill="white"
                    />
                    <rect
                        width="13.6658"
                        height="4"
                        rx="2"
                        transform="matrix(0.707107 -0.707107 -0.707107 -0.707107 38.8284 34.4912)"
                        fill="white"
                    />
                    <rect x="8" y="4" width="42" height="56" rx="4.75" className="base" />
                    <g className="mix-blend-multiply">
                        <rect
                            x="60.4916"
                            y="34.2393"
                            width="21"
                            height="5"
                            rx="2.5"
                            transform="rotate(-180 60.4916 34.2393)"
                            className="primary"
                        />
                        <rect
                            x="45.4916"
                            y="41.2393"
                            width="13.3093"
                            height="4"
                            rx="2"
                            transform="rotate(-135 45.4916 41.2393)"
                            className="primary"
                        />
                        <rect
                            width="13.6658"
                            height="4"
                            rx="2"
                            transform="matrix(0.707107 -0.707107 -0.707107 -0.707107 38.8284 34.4912)"
                            className="primary"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

BoxWithRightArrow.displayName = "BoxWithRightArrow";

export default BoxWithRightArrow;
