// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Calendar = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Calendar} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path className="base" d="M4,21H60V58a2,2,0,0,1-2,2H6a2,2,0,0,1-2-2Z" />
                            <g className="mix-blend-multiply ">
                                <path className="primary" d="M6,7H58a2,2,0,0,1,2,2V24H4V9A2,2,0,0,1,6,7Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M16.49,4h-1A1.52,1.52,0,0,0,14,5.51v7A1.52,1.52,0,0,0,15.51,14h1A1.52,1.52,0,0,0,18,12.49v-7A1.52,1.52,0,0,0,16.49,4Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M48.49,4h-1A1.52,1.52,0,0,0,46,5.51v7A1.52,1.52,0,0,0,47.51,14h1A1.52,1.52,0,0,0,50,12.49v-7A1.52,1.52,0,0,0,48.49,4Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M27.5,29h-3A1.5,1.5,0,0,0,23,30.5v3A1.5,1.5,0,0,0,24.5,35h3A1.5,1.5,0,0,0,29,33.5v-3A1.5,1.5,0,0,0,27.5,29Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M39.5,29h-3A1.5,1.5,0,0,0,35,30.5v3A1.5,1.5,0,0,0,36.5,35h3A1.5,1.5,0,0,0,41,33.5v-3A1.5,1.5,0,0,0,39.5,29Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M51.5,29h-3A1.5,1.5,0,0,0,47,30.5v3A1.5,1.5,0,0,0,48.5,35h3A1.5,1.5,0,0,0,53,33.5v-3A1.5,1.5,0,0,0,51.5,29Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M27.5,39h-3A1.5,1.5,0,0,0,23,40.5v3A1.5,1.5,0,0,0,24.5,45h3A1.5,1.5,0,0,0,29,43.5v-3A1.5,1.5,0,0,0,27.5,39Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M39.5,39h-3A1.5,1.5,0,0,0,35,40.5v3A1.5,1.5,0,0,0,36.5,45h3A1.5,1.5,0,0,0,41,43.5v-3A1.5,1.5,0,0,0,39.5,39Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M51.5,39h-3A1.5,1.5,0,0,0,47,40.5v3A1.5,1.5,0,0,0,48.5,45h3A1.5,1.5,0,0,0,53,43.5v-3A1.5,1.5,0,0,0,51.5,39Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M15.5,39h-3A1.5,1.5,0,0,0,11,40.5v3A1.5,1.5,0,0,0,12.5,45h3A1.5,1.5,0,0,0,17,43.5v-3A1.5,1.5,0,0,0,15.5,39Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M27.5,49h-3A1.5,1.5,0,0,0,23,50.5v3A1.5,1.5,0,0,0,24.5,55h3A1.5,1.5,0,0,0,29,53.5v-3A1.5,1.5,0,0,0,27.5,49Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M39.5,49h-3A1.5,1.5,0,0,0,35,50.5v3A1.5,1.5,0,0,0,36.5,55h3A1.5,1.5,0,0,0,41,53.5v-3A1.5,1.5,0,0,0,39.5,49Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M15.5,49h-3A1.5,1.5,0,0,0,11,50.5v3A1.5,1.5,0,0,0,12.5,55h3A1.5,1.5,0,0,0,17,53.5v-3A1.5,1.5,0,0,0,15.5,49Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Calendar.displayName = "Calendar";

export default Calendar;
