// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const CarPictogram = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.CarPictogram} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M13.3263 13.6033C13.5151 12.6706 14.3349 12 15.2866 12H48.7134C49.6651 12 50.4849 12.6705 50.6737 13.6033L54.1816 30.9366C54.4323 32.1755 53.4853 33.3333 52.2214 33.3333H11.7786C10.5147 33.3333 9.56766 32.1755 9.81838 30.9366L13.3263 13.6033Z"
                        className="base"
                    />
                    <rect
                        x="60"
                        y="32"
                        width="14.6667"
                        height="56"
                        rx="3.27529"
                        transform="rotate(90 60 32)"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <rect
                            x="60"
                            y="32"
                            width="14.6667"
                            height="56"
                            rx="3.27529"
                            transform="rotate(90 60 32)"
                            className="primary"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <circle cx="11.3693" cy="39.0209" r="2.45647" className="primary" />
                    </g>
                    <g className="mix-blend-multiply">
                        <circle cx="52.3105" cy="39.0209" r="2.45647" className="primary" />
                    </g>
                    <path
                        d="M49.3333 46.6665H54.6667V51.6955C54.6667 52.6 53.9335 53.3332 53.029 53.3332H50.971C50.0665 53.3332 49.3333 52.6 49.3333 51.6955V46.6665Z"
                        fill="white"
                    />
                    <path
                        d="M49.3333 46.6665H54.6667V51.6955C54.6667 52.6 53.9335 53.3332 53.029 53.3332H50.971C50.0665 53.3332 49.3333 52.6 49.3333 51.6955V46.6665Z"
                        fill="white"
                    />
                    <path
                        d="M9.33333 46.6665H14.6667V51.6955C14.6667 52.6 13.9335 53.3332 13.029 53.3332H10.971C10.0665 53.3332 9.33333 52.6 9.33333 51.6955V46.6665Z"
                        fill="white"
                    />
                    <path
                        d="M9.33333 46.6665H14.6667V51.6955C14.6667 52.6 13.9335 53.3332 13.029 53.3332H10.971C10.0665 53.3332 9.33333 52.6 9.33333 51.6955V46.6665Z"
                        fill="white"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M49.3333 46.6665H54.6667V51.6955C54.6667 52.6 53.9335 53.3332 53.029 53.3332H50.971C50.0665 53.3332 49.3333 52.6 49.3333 51.6955V46.6665Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M9.33333 46.6665H14.6667V51.6955C14.6667 52.6 13.9335 53.3332 13.029 53.3332H10.971C10.0665 53.3332 9.33333 52.6 9.33333 51.6955V46.6665Z"
                            className="base"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

CarPictogram.displayName = "CarPictogram";

export default CarPictogram;
