// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Cash = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Cash} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M11 57.7654V56H60V57.7654C60 58.358 59.7893 58.9264 59.4142 59.3455C59.0391 59.7646 58.5304 60 58 60H13C12.4696 60 11.9609 59.7646 11.5858 59.3455C11.2107 58.9264 11 58.358 11 57.7654Z"
                        className="base"
                    />
                    <path
                        d="M4 27L4 6.05174C4 5.50758 4.21071 4.98571 4.58579 4.60094C4.96086 4.21616 5.46957 4 6 4L51 4C51.5304 4 52.0391 4.21616 52.4142 4.60094C52.7893 4.98571 53 5.50758 53 6.05174V27L4 27Z"
                        className="base"
                    />
                    <path
                        d="M11 56L11 35.0517C11 34.5076 11.2107 33.9857 11.5858 33.6009C11.9609 33.2162 12.4696 33 13 33H58C58.5304 33 59.0391 33.2162 59.4142 33.6009C59.7893 33.9857 60 34.5076 60 35.0517V56H11Z"
                        className="base"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M37.5 10.0898H47V11.2398H43C43.5389 11.7822 43.8894 12.4833 44 13.2398H47V14.3798H43.92C43.7796 15.0886 43.4315 15.7396 42.92 16.2498C42.6058 16.5839 42.2286 16.8524 41.81 17.0398L44.73 22.0398H43.39L40.66 17.3798H37.47V16.2098H40.52C41.177 16.2079 41.8064 15.9454 42.27 15.4798C42.5852 15.1731 42.81 14.7857 42.92 14.3598H37.5V13.2198H43C42.8837 12.6594 42.5794 12.1555 42.1374 11.7917C41.6954 11.4279 41.1424 11.2262 40.57 11.2198H37.47V10.1198L37.5 10.0898Z"
                        className="secondary"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M44.5 39.0898H54V40.2398H50C50.5389 40.7822 50.8894 41.4833 51 42.2398H54V43.3798H50.92C50.7796 44.0886 50.4315 44.7396 49.92 45.2498C49.6058 45.5839 49.2286 45.8524 48.81 46.0398L51.73 51.0398H50.39L47.66 46.3798H44.47V45.2098H47.52C48.177 45.2079 48.8064 44.9454 49.27 44.4798C49.5852 44.1731 49.81 43.7857 49.92 43.3598H44.5V42.2198H50C49.8837 41.6594 49.5794 41.1555 49.1374 40.7917C48.6954 40.4279 48.1424 40.2262 47.57 40.2198H44.47V39.1198L44.5 39.0898Z"
                        className="secondary"
                    />
                    <path opacity="0.5" d="M23 33H16V60H23V33Z" className="primary" />
                    <path
                        d="M4 28.7654V27L53 27V28.7654C53 29.358 52.7893 29.9264 52.4142 30.3455C52.0391 30.7646 51.5304 31 51 31L6 31C5.46957 31 4.96086 30.7646 4.58579 30.3455C4.21072 29.9264 4 29.358 4 28.7654Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M11 57.7654V56H60V57.7654C60 58.358 59.7893 58.9264 59.4142 59.3455C59.0391 59.7646 58.5304 60 58 60H13C12.4696 60 11.9609 59.7646 11.5858 59.3455C11.2107 58.9264 11 58.358 11 57.7654Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 28.7654V27L53 27V28.7654C53 29.358 52.7893 29.9264 52.4142 30.3455C52.0391 30.7646 51.5304 31 51 31L6 31C5.46957 31 4.96086 30.7646 4.58579 30.3455C4.21072 29.9264 4 29.358 4 28.7654Z"
                            className="base"
                        />
                    </g>
                    <path opacity="0.5" d="M16 4H9V31H16V4Z" className="primary" />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Cash.displayName = "Cash";

export default Cash;
