// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Chord = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Chord} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base mix-blend"
                                d="M26,14.43a1.49,1.49,0,0,0-.44-1,1.5,1.5,0,0,0-2.12,0,1.49,1.49,0,0,0-.44,1V44.31A9,9,0,0,0,17.44,42,9,9,0,0,0,8.79,54.69,9,9,0,0,0,26,51V14.43Z"
                            />
                            <path
                                className="base mix-blend"
                                d="M53,9.44a1.5,1.5,0,0,0-3,0V39.32a9,9,0,0,0-14.7,4.4A9,9,0,0,0,39.93,54,9,9,0,0,0,53,46V9.44Z"
                            />
                            <path
                                className="primary"
                                d="M53,11.77,23,17V11.32a2.92,2.92,0,0,1,.68-1.77,3,3,0,0,1,1.63-1l25.38-4.5a1.85,1.85,0,0,1,1.63.35A1.86,1.86,0,0,1,53,5.93Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Chord.displayName = "Chord";

export default Chord;
