// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const CircleWithExclamationMark = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.CircleWithExclamationMark} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>

                    <path
                        d="M32 60C47.464 60 60 47.464 60 32C60 16.536 47.464 4 32 4C16.536 4 4 16.536 4 32C4 47.464 16.536 60 32 60Z"
                        className="base"
                    />
                    <path
                        d="M28.111 15.1071C28.0503 13.4093 29.4102 12 31.1091 12H32.8909C34.5898 12 35.9497 13.4093 35.889 15.1071L35.1033 37.1071C35.0457 38.7212 33.7204 40 32.1052 40H31.8948C30.2796 40 28.9543 38.7212 28.8967 37.1071L28.111 15.1071Z"
                        className="primary"
                    />
                    <circle cx="32" cy="46" r="4" className="primary" />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

CircleWithExclamationMark.displayName = "CircleWithExclamationMark";

export default CircleWithExclamationMark;
