// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const CircleWithTick = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.CircleWithTick} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M32 60C47.464 60 60 47.464 60 32C60 16.536 47.464 4 32 4C16.536 4 4 16.536 4 32C4 47.464 16.536 60 32 60Z"
                        className="base"
                    />
                    <path
                        d="M47.56 20C47.2813 19.7204 46.9501 19.4985 46.5855 19.347C46.2208 19.1956 45.8298 19.1177 45.435 19.1177C45.0402 19.1177 44.6492 19.1956 44.2845 19.347C43.9199 19.4985 43.5887 19.7204 43.31 20L25.64 37.66L20.69 32.71C20.4083 32.431 20.0744 32.2101 19.7074 32.0601C19.3404 31.9101 18.9474 31.8338 18.5509 31.8357C18.1544 31.8376 17.7621 31.9175 17.3965 32.0709C17.0309 32.2244 16.6991 32.4484 16.42 32.73C16.1409 33.0117 15.9201 33.3456 15.7701 33.7127C15.6201 34.0797 15.5438 34.4727 15.5457 34.8692C15.5475 35.2657 15.6275 35.6579 15.7809 36.0236C15.9344 36.3892 16.1583 36.721 16.44 37L21.39 41.95L23.51 44C23.7887 44.2797 24.1199 44.5016 24.4845 44.653C24.8492 44.8045 25.2402 44.8824 25.635 44.8824C26.0298 44.8824 26.4208 44.8045 26.7855 44.653C27.1501 44.5016 27.4813 44.2797 27.76 44L47.56 24.2C48.1097 23.6393 48.4176 22.8853 48.4176 22.1C48.4176 21.3148 48.1097 20.5608 47.56 20Z"
                        className="primary"
                    />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

CircleWithTick.displayName = "CircleWithTick";

export default CircleWithTick;
