// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Craftsmanship = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Craftsmanship} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path d="M4 4V60H60L4 4ZM14 28L37 51H14V28Z" className="base" />
                    <path
                        d="M17.0951 9.59563L22.9358 3.75493C23.1233 3.56739 23.3777 3.46203 23.6429 3.46203C23.9081 3.46203 24.1625 3.56739 24.35 3.75493L57.6265 37.0314L50.3716 44.2863L17.0951 11.0098C16.9076 10.8223 16.8022 10.568 16.8022 10.3027C16.8022 10.0375 16.9076 9.78316 17.0951 9.59563Z"
                        className="primary"
                    />
                    <path
                        d="M17.1027 9.6049L22.9434 3.7642C23.1309 3.57667 23.3853 3.47131 23.6505 3.47131C23.9157 3.47131 24.1701 3.57667 24.3576 3.7642L26.1961 5.60268L18.9412 12.8576L17.1027 11.0191C16.9151 10.8316 16.8098 10.5772 16.8098 10.312C16.8098 10.0468 16.9151 9.79244 17.1027 9.6049Z"
                        className="primary"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M24.3599 7.4334L20.6829 11.1104L52.1209 42.5483L55.7978 38.8714L24.3599 7.4334Z"
                            className="primary"
                        />
                    </g>
                    <path
                        d="M57.43 45.72L50.34 44.26L57.59 37L59.05 44.09C59.0716 44.3085 59.0446 44.5291 58.9709 44.736C58.8973 44.9429 58.7789 45.1309 58.6241 45.2867C58.4693 45.4424 58.2819 45.562 58.0755 45.6369C57.8691 45.7119 57.6487 45.7402 57.43 45.72Z"
                        fill="white"
                    />
                    <path
                        d="M57.43 45.72L50.34 44.26L57.59 37L59.05 44.09C59.0716 44.3085 59.0446 44.5291 58.9709 44.736C58.8973 44.9429 58.7789 45.1309 58.6241 45.2867C58.4693 45.4424 58.2819 45.562 58.0755 45.6369C57.8691 45.7119 57.6487 45.7402 57.43 45.72Z"
                        className="tertiary"
                    />
                    <path d="M59.87 46.5302L58.51 41.4502L54.79 45.1602L59.87 46.5302Z" fill="#6B7073" />
                    <path
                        d="M16.8501 7.931L21.2766 3.50451C21.6517 3.12944 22.1604 2.91873 22.6908 2.91873C23.2213 2.91873 23.73 3.12944 24.105 3.50451L26.2264 5.62583L18.9714 12.8807L16.8501 10.7594C16.4751 10.3844 16.2643 9.87565 16.2643 9.34521C16.2643 8.81478 16.4751 8.30607 16.8501 7.931Z"
                        className="secondary"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 20H9.5C9.77614 20 10 20.2239 10 20.5V20.5C10 20.7761 9.77614 21 9.5 21H4V20Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 30H9.5C9.77614 30 10 30.2239 10 30.5V30.5C10 30.7761 9.77614 31 9.5 31H4V30Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 40H9.5C9.77614 40 10 40.2239 10 40.5V40.5C10 40.7761 9.77614 41 9.5 41H4V40Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 50H9.5C9.77614 50 10 50.2239 10 50.5V50.5C10 50.7761 9.77614 51 9.5 51H4V50Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 25H6.5C6.77614 25 7 25.2239 7 25.5V25.5C7 25.7761 6.77614 26 6.5 26H4V25Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 35H6.5C6.77614 35 7 35.2239 7 35.5V35.5C7 35.7761 6.77614 36 6.5 36H4V35Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M4 45H6.5C6.77614 45 7 45.2239 7 45.5V45.5C7 45.7761 6.77614 46 6.5 46H4V45Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M14 60L14 54.5C14 54.2239 14.2239 54 14.5 54V54C14.7761 54 15 54.2239 15 54.5L15 60L14 60Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M24 60L24 54.5C24 54.2239 24.2239 54 24.5 54V54C24.7761 54 25 54.2239 25 54.5L25 60L24 60Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M34 60L34 54.5C34 54.2239 34.2239 54 34.5 54V54C34.7761 54 35 54.2239 35 54.5L35 60L34 60Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M44 60L44 54.5C44 54.2239 44.2239 54 44.5 54V54C44.7761 54 45 54.2239 45 54.5L45 60L44 60Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M19 60L19 57.5C19 57.2239 19.2239 57 19.5 57V57C19.7761 57 20 57.2239 20 57.5L20 60L19 60Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M29 60L29 57.5C29 57.2239 29.2239 57 29.5 57V57C29.7761 57 30 57.2239 30 57.5L30 60L29 60Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M39 60L39 57.5C39 57.2239 39.2239 57 39.5 57V57C39.7761 57 40 57.2239 40 57.5L40 60L39 60Z"
                            className="base"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Craftsmanship.displayName = "Craftsmanship";

export default Craftsmanship;
