// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const DocumentWithRedBadge = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.DocumentWithRedBadge} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <g clipPath="url(#clipPath)">
                                <path
                                    className="base"
                                    d="M24.16.67,8.71,15.33a2.51,2.51,0,0,0-.54.76A2.2,2.2,0,0,0,8,17V61.71a2.08,2.08,0,0,0,.19.88,2.12,2.12,0,0,0,.52.74,2.5,2.5,0,0,0,1.71.67H49.59a2.48,2.48,0,0,0,1.7-.67,2.29,2.29,0,0,0,.53-.74,2.23,2.23,0,0,0,.18-.88V2.29a2.23,2.23,0,0,0-.18-.88,2.29,2.29,0,0,0-.53-.74A2.48,2.48,0,0,0,49.59,0H25.88A2.64,2.64,0,0,0,25,.17,2.59,2.59,0,0,0,24.16.67Z"
                                />
                                <g className="mix-blend-multiply">
                                    <path
                                        className="base"
                                        d="M23.31,1.14V12.9a1.78,1.78,0,0,1-.16.75,1.81,1.81,0,0,1-.43.63,2.08,2.08,0,0,1-1.42.58H9.18Z"
                                    />
                                </g>
                                <g className="mix-blend-multiply">
                                    <path
                                        className="primary"
                                        d="M50,38.05a10,10,0,1,0-7.07-2.93A10,10,0,0,0,50,38.05Z"
                                    />
                                    <g className="mix-blend-multiply">
                                        <path
                                            className="primary"
                                            d="M50,35.12a7.08,7.08,0,0,0,6.94-8.45,7.08,7.08,0,0,0-12.82-2.55,7.07,7.07,0,0,0,5.88,11Z"
                                        />
                                    </g>
                                    <path
                                        className="primary"
                                        d="M50,35.55H47.5a1.26,1.26,0,0,0-1.25,1.25V48.6a1.26,1.26,0,0,0,.22.7,1.22,1.22,0,0,0,.57.46,1.34,1.34,0,0,0,.74.06,1.31,1.31,0,0,0,.63-.37l.68-.71a1,1,0,0,1,.41-.29,1.19,1.19,0,0,1,1,0,1,1,0,0,1,.41.29l.68.71a1.31,1.31,0,0,0,.63.37,1.34,1.34,0,0,0,.74-.06,1.22,1.22,0,0,0,.57-.46,1.26,1.26,0,0,0,.22-.7V36.8a1.26,1.26,0,0,0-1.25-1.25Z"
                                    />
                                </g>
                                <g className="mix-blend-multiply">
                                    <path className="base" d="M30.6,25H5.4a1.5,1.5,0,0,0,0,3H30.6a1.5,1.5,0,0,0,0-3Z" />
                                </g>
                                <g className="mix-blend-multiply">
                                    <path className="base" d="M22.5,32H5.5a1.5,1.5,0,0,0,0,3h17a1.5,1.5,0,0,0,0-3Z" />
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

DocumentWithRedBadge.displayName = "DocumentWithRedBadge";

export default DocumentWithRedBadge;
