// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const DocumentWithDetails = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.DocumentWithDetails} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base"
                                d="M39.9.67,55.29,15.33a2.45,2.45,0,0,1,.53.74A2.12,2.12,0,0,1,56,17V61.71a2.21,2.21,0,0,1-.7,1.62,2.49,2.49,0,0,1-1.7.67H10.37a2.49,2.49,0,0,1-1.7-.67,2.06,2.06,0,0,1-.5-.74A2.22,2.22,0,0,1,8,61.71V2.29a2.22,2.22,0,0,1,.17-.88,2.06,2.06,0,0,1,.5-.74A2.49,2.49,0,0,1,10.37,0H38.19a2.69,2.69,0,0,1,.93.17A2.67,2.67,0,0,1,39.9.67Z"
                            />
                            <path className="primary" d="M45.12,60a7,7,0,1,0-4.95-2A7,7,0,0,0,45.12,60Z" />
                            <path
                                fillRule="evenodd"
                                className="secondary"
                                d="M43.61,53.66a.76.76,0,0,0,.23.17.87.87,0,0,0,.28.05.63.63,0,0,0,.51-.22l2.73-2.86a.57.57,0,0,1,.18-.12H48a.66.66,0,0,1,.17.12.44.44,0,0,1,.12.18.51.51,0,0,1,0,.44.44.44,0,0,1-.12.18L44.5,55.4a.66.66,0,0,1-.17.12.47.47,0,0,1-.42,0,.66.66,0,0,1-.17-.12l-1.62-1.74a.59.59,0,0,1-.13-.18.71.71,0,0,1,0-.21.57.57,0,0,1,0-.22.59.59,0,0,1,.13-.18.66.66,0,0,1,.17-.12h.41a.57.57,0,0,1,.18.12Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M40,.81V13a1.92,1.92,0,0,0,.17.78,2,2,0,0,0,.45.65,2.18,2.18,0,0,0,1.51.6H55Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M15.52,30h34a1.5,1.5,0,0,0,0-3h-34a1.5,1.5,0,0,0,0,3Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M15.52,36h22a1.5,1.5,0,0,0,0-3h-22a1.5,1.5,0,0,0,0,3Z" />
                            </g>
                            <g>
                                <path className="mix-blend-multiply base" d="M29,6H14V21H29Z" />
                                <path
                                    className="base"
                                    d="M27.84,20.39v1.93c0,.6-12.66.6-12.66,0V20.39c0-4.51,2.94-6.33,6.33-6.33S27.84,15.88,27.84,20.39Z"
                                />
                            </g>
                            <g>
                                <path
                                    className="base"
                                    d="M21.51,14.06a2.89,2.89,0,0,0,2.66-1.78,2.77,2.77,0,0,0,.16-1.66,2.83,2.83,0,0,0-2.26-2.26,2.77,2.77,0,0,0-1.66.16,2.89,2.89,0,0,0-1.78,2.66,2.77,2.77,0,0,0,.22,1.1,3,3,0,0,0,.62.94A2.89,2.89,0,0,0,21.51,14.06Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

DocumentWithDetails.displayName = "DocumentWithDetails";

export default DocumentWithDetails;
