// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const DocumentWithCode = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.DocumentWithCode} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M48.08 64H9C8.46957 64 7.96086 63.7893 7.58579 63.4142C7.21071 63.0391 7 62.5304 7 62V14L21 0H48.08C48.6104 0 49.1191 0.210714 49.4942 0.585786C49.8693 0.960859 50.08 1.46957 50.08 2V62C50.08 62.5304 49.8693 63.0391 49.4942 63.4142C49.1191 63.7893 48.6104 64 48.08 64Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M21 0L7 14H19C19.5304 14 20.0391 13.7893 20.4142 13.4142C20.7893 13.0391 21 12.5304 21 12V0Z"
                            className="base"
                        />
                    </g>
                    <path
                        d="M31.2937 32H13.754C12.7853 32 12 32.8954 12 34C12 35.1046 12.7853 36 13.754 36H31.2937C32.2623 36 33.0476 35.1046 33.0476 34C33.0476 32.8954 32.2623 32 31.2937 32Z"
                        className="tertiary"
                    />
                    <path
                        d="M19.9238 40H13.981C12.8869 40 12 40.8954 12 42C12 43.1046 12.8869 44 13.981 44H19.9238C21.0179 44 21.9048 43.1046 21.9048 42C21.9048 40.8954 21.0179 40 19.9238 40Z"
                        className="primary"
                    />
                    <path
                        d="M54.4021 40H25.7884C24.8007 40 24 40.8954 24 42C24 43.1046 24.8007 44 25.7884 44H54.4021C55.3898 44 56.1905 43.1046 56.1905 42C56.1905 40.8954 55.3898 40 54.4021 40Z"
                        className="tertiary"
                    />
                    <path
                        d="M42.4021 48H13.7884C12.8007 48 12 48.8954 12 50C12 51.1046 12.8007 52 13.7884 52H42.4021C43.3898 52 44.1905 51.1046 44.1905 50C44.1905 48.8954 43.3898 48 42.4021 48Z"
                        className="secondary"
                    />
                    <path
                        d="M57.5635 32H37.9603C36.8777 32 36 32.8954 36 34C36 35.1046 36.8777 36 37.9603 36H57.5635C58.6461 36 59.5238 35.1046 59.5238 34C59.5238 32.8954 58.6461 32 57.5635 32Z"
                        className="secondary"
                    />
                    <rect x="12" y="24" width="32" height="4" rx="2" className="primary" />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

DocumentWithCode.displayName = "DocumentWithCode";

export default DocumentWithCode;
