// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Droplets = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Droplets} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M53.3335 46.0539C53.3335 52.521 48.2497 57.7636 41.9786 57.7636C35.7075 57.7636 30.6238 52.521 30.6238 46.0539C30.6238 36.9464 40.0862 26.5378 41.9786 26.5378C43.2403 26.5378 53.3335 36.9464 53.3335 46.0539Z"
                        fill="white"
                    />
                    <path
                        d="M47.6559 38.6019C47.6559 49.1844 39.0771 57.7632 28.4946 57.7632C17.9121 57.7632 9.33334 49.1844 9.33334 38.6019C9.33334 23.6987 25.3011 6.6665 28.4946 6.6665C30.6236 6.6665 47.6559 23.6987 47.6559 38.6019Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M53.3335 46.0537C53.3335 52.5208 48.2498 57.7634 41.9787 57.7634C35.7076 57.7634 30.6238 52.5208 30.6238 46.0537C30.6238 36.9462 40.0862 26.5376 41.9787 26.5376C43.2403 26.5376 53.3335 36.9462 53.3335 46.0537Z"
                            className="primary"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Droplets.displayName = "Droplets";

export default Droplets;
