// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const EVRecharge = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.EVRecharge} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M12 10C12 8.89543 12.8954 8 14 8H34C35.1046 8 36 8.89543 36 10V48H12V10Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M25.7381 29.0001H22.5451C22.4457 28.9983 22.3488 29.0316 22.2716 29.0942C22.1943 29.1567 22.1416 29.2446 22.1227 29.3422L21.0077 35.1538C20.9957 35.2156 20.9977 35.2792 21.0135 35.3402C21.0293 35.4011 21.0585 35.4577 21.099 35.5058C21.1395 35.554 21.1902 35.5925 21.2475 35.6186C21.3048 35.6446 21.3672 35.6576 21.4301 35.6564H24.9398L23.9515 39.9476C23.9491 39.9572 23.9502 39.9674 23.9546 39.9763C23.9589 39.9852 23.9663 39.9923 23.9754 39.9964C23.9844 40.0004 23.9946 40.0011 24.0042 39.9984C24.0137 39.9956 24.022 39.9896 24.0276 39.9813L27.305 34.2838C27.3422 34.2194 27.3617 34.1464 27.3616 34.0722C27.3616 33.9979 27.3419 33.9249 27.3046 33.8607C27.2674 33.7964 27.2138 33.7431 27.1494 33.7062C27.0849 33.6692 27.0119 33.6499 26.9376 33.6502H24.3697L26.1267 29.5914C26.1548 29.527 26.1664 29.4566 26.1604 29.3866C26.1544 29.3166 26.1311 29.2492 26.0925 29.1905C26.054 29.1318 26.0013 29.0836 25.9395 29.0504C25.8776 29.0171 25.8084 28.9998 25.7381 29.0001V29.0001Z"
                            className="primary"
                        />
                    </g>
                    <rect x="16" y="12" width="16" height="12" rx="1" className="tertiary" />
                    <g className="mix-blend-multiply">
                        <path
                            d="M19.584 21V15.4H23.112V16.048H20.312V17.696H22.584V18.352H20.312V20.344H23.2V21H19.584ZM25.7151 21L23.6111 15.4H24.3551L26.0831 20.16L27.8191 15.4H28.5631L26.4591 21H25.7151Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M19.584 21V15.4H23.112V16.048H20.312V17.696H22.584V18.352H20.312V20.344H23.2V21H19.584ZM25.7151 21L23.6111 15.4H24.3551L26.0831 20.16L27.8191 15.4H28.5631L26.4591 21H25.7151Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M19.584 21V15.4H23.112V16.048H20.312V17.696H22.584V18.352H20.312V20.344H23.2V21H19.584ZM25.7151 21L23.6111 15.4H24.3551L26.0831 20.16L27.8191 15.4H28.5631L26.4591 21H25.7151Z"
                            className="base"
                        />
                    </g>
                    <path
                        d="M36 28C36.5523 28 37 28.4477 37 29V32C37 32.5523 36.5523 33 36 33V28Z"
                        className="secondary"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M36 28C36.5523 28 37 28.4477 37 29V32C37 32.5523 36.5523 33 36 33V28Z"
                            className="secondary"
                        />
                    </g>
                    <path
                        d="M55 24C55 24.5523 54.5523 25 54 25L52 25C51.4477 25 51 24.5523 51 24L55 24Z"
                        className="secondary"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M55 24C55 24.5523 54.5523 25 54 25L52 25C51.4477 25 51 24.5523 51 24L55 24Z"
                            className="secondary"
                        />
                    </g>
                    <path
                        d="M37 30.3778H40.4C42.0569 30.3778 43.4 31.7209 43.4 33.3778V44C43.4 45.6569 44.7431 47 46.4 47H48.52H51.08C52.1404 47 53 46.1404 53 45.08V29.4V25"
                        stroke="#8DB1D1"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M46.4683 13.9145L48.5 10.5517L48.9311 9.88284C49.2407 9.40242 49.8892 9.27876 50.3539 9.61154L55.5823 13.356C55.8445 13.5438 56 13.8465 56 14.169V23C56 23.5523 55.5523 24 55 24H51.1469C50.5946 24 50.1469 23.5523 50.1469 23V18.2938C50.1469 17.9786 49.9983 17.6819 49.746 17.4931L46.725 15.2323C46.3135 14.9243 46.2025 14.3545 46.4683 13.9145Z"
                            className="primary"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M46.4683 13.9145L48.5 10.5517L48.9311 9.88284C49.2407 9.40242 49.8892 9.27876 50.3539 9.61154L55.5823 13.356C55.8445 13.5438 56 13.8465 56 14.169V23C56 23.5523 55.5523 24 55 24H51.1469C50.5946 24 50.1469 23.5523 50.1469 23V18.2938C50.1469 17.9786 49.9983 17.6819 49.746 17.4931L46.725 15.2323C46.3135 14.9243 46.2025 14.3545 46.4683 13.9145Z"
                            className="primary"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M8 50C8 48.8954 8.89543 48 10 48H38C39.1046 48 40 48.8954 40 50V54C40 55.1046 39.1046 56 38 56H10C8.89543 56 8 55.1046 8 54V50Z"
                            className="base"
                        />
                    </g>
                    <path
                        d="M8 50C8 48.8954 8.89543 48 10 48H38C39.1046 48 40 48.8954 40 50V54C40 55.1046 39.1046 56 38 56H10C8.89543 56 8 55.1046 8 54V50Z"
                        className="secondary"
                    />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

EVRecharge.displayName = "EVRecharge";

export default EVRecharge;
