// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const GrowthMindset = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.GrowthMindset} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_2" data-name="Layer 2">
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M24.31,24.2a.61.61,0,0,1,.61.61V58.38a1.56,1.56,0,0,0,1.56,1.56h11A1.56,1.56,0,0,0,39,58.38V24.81a.61.61,0,0,1,.61-.61h4.27a1.56,1.56,0,0,0,1.31-2.41L33.69,4.7a1.57,1.57,0,0,0-2.59,0L18.83,21.75a1.55,1.55,0,0,0,1.28,2.45Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M45.65,36.36a.61.61,0,0,1,.61.61V59a1,1,0,0,0,1.05,1h7.33a1,1,0,0,0,1-1V37a.61.61,0,0,1,.6-.61H59a1,1,0,0,0,.87-1.59L52.13,23.46a1.06,1.06,0,0,0-1.73,0l-8.21,11.3a1,1,0,0,0,.86,1.62Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M7.65,36.36a.61.61,0,0,1,.61.61V59a1,1,0,0,0,1.05,1h7.33a1,1,0,0,0,1.05-1V37a.61.61,0,0,1,.6-.61H21a1,1,0,0,0,.87-1.59L14.13,23.46a1.06,1.06,0,0,0-1.73,0L4.19,34.74a1,1,0,0,0,.86,1.62Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

GrowthMindset.displayName = "GrowthMindset";

export default GrowthMindset;
