// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const GuyFawkesMask = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.GuyFawkesMask} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base"
                                d="M32.1,4A51.26,51.26,0,0,1,52.28,8.12a2.71,2.71,0,0,1,1.23,1,2.85,2.85,0,0,1,.49,1.5v22a5.52,5.52,0,0,1-.29,1.8,33,33,0,0,1-6,10.38A39.47,39.47,0,0,1,33.45,55.43a3.65,3.65,0,0,1-2.9,0A39.5,39.5,0,0,1,16.29,44.78a34,34,0,0,1-5.94-10.29,5.48,5.48,0,0,1-.35-2V10.61a2.7,2.7,0,0,1,1.72-2.49A52.63,52.63,0,0,1,32.1,4Z"
                            />
                            <path
                                className="primary"
                                d="M27.81,43.38a2,2,0,0,1,.45-1.64,2,2,0,0,1,1.55-.7H35a2,2,0,0,1,.86.17,2.09,2.09,0,0,1,.69.53,1.92,1.92,0,0,1,.41.77,2,2,0,0,1,0,.88l-2.64,15a2,2,0,0,1-.7,1.13,2,2,0,0,1-2.51,0,2,2,0,0,1-.7-1.13C29.57,53.42,28.69,48.43,27.81,43.38Z"
                            />
                            <path
                                className="primary"
                                d="M30.57,31.62l1.31-1.43a.44.44,0,0,1,.15-.12.42.42,0,0,1,.19,0h.59l1.42,1.56,1.15,1.26a1.05,1.05,0,0,0,.73.32H44a1.13,1.13,0,0,0,.6-.14l1.19-.76a.36.36,0,0,1,.25-.06.45.45,0,0,1,.23.11.38.38,0,0,1,.11.23.45.45,0,0,1-.05.25c-.32.49-.65,1-1,1.48a.72.72,0,0,1-.26.23.76.76,0,0,1-.33.11c-1.51.08-3,.14-4.54.21s-3,.12-4.47.2a1.08,1.08,0,0,1-.4-.06,1.13,1.13,0,0,1-.35-.21l-1.89-1.83a1,1,0,0,0-1.38,0l-1.89,1.82a1.13,1.13,0,0,1-.35.21,1.08,1.08,0,0,1-.4.06c-1.49-.08-3-.14-4.47-.2l-4.54-.21a.76.76,0,0,1-.33-.11.72.72,0,0,1-.26-.23c-.35-.5-.68-1-1-1.48a.45.45,0,0,1,0-.25.38.38,0,0,1,.11-.23.45.45,0,0,1,.23-.11.36.36,0,0,1,.25.06L20.2,33a1,1,0,0,0,.56.17h7.93a1.05,1.05,0,0,0,.73-.32Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="secondary"
                                    d="M32.5,16a1.46,1.46,0,0,1,1.06.44A1.5,1.5,0,0,1,34,17.54v12a1.52,1.52,0,0,1-.44,1.06A1.5,1.5,0,0,1,32.5,31h0a1.5,1.5,0,0,1-1.06-.44A1.52,1.52,0,0,1,31,29.54v-12a1.5,1.5,0,0,1,.44-1.06A1.46,1.46,0,0,1,32.5,16Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="secondary"
                                    d="M17,19H47a1,1,0,0,1,.71.29A1,1,0,0,1,48,20a1,1,0,0,1-1,1H17a1,1,0,0,1-1-1,1,1,0,0,1,.29-.71A1,1,0,0,1,17,19Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

GuyFawkesMask.displayName = "GuyFawkesMask";

export default GuyFawkesMask;
