// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Hat = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Hat} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M13.3333 49.0496V30.1824C13.3333 29.7662 13.7428 29.4737 14.1365 29.6084L27.6942 34.2497C32.6667 35.3338 34 34.6671 37.3333 34.0005L49.8596 29.6163C50.2541 29.4782 50.6667 29.771 50.6667 30.1888V49.0496C50.6667 49.2297 50.59 49.3988 50.4491 49.5109C42.3601 55.9411 21.6399 55.9411 13.5509 49.5109C13.41 49.3988 13.3333 49.2297 13.3333 49.0496Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M13.3333 49.3338V41.3335C21.3333 47.9999 42.6667 48.0002 50.6667 41.3338V49.3338C42.6667 56.0002 21.3333 56.0002 13.3333 49.3338Z"
                            className="base"
                        />
                    </g>
                    <path d="M57.3333 26.6665L56 27.3999V37.3332H57.3333V26.6665Z" className="primary" />
                    <circle cx="56.5949" cy="39.2615" r="3.26153" className="primary" />
                    <path
                        d="M31.8376 17.3786L2.0044 25.6656C1.41986 25.828 1.4093 26.653 1.9895 26.8303L31.8227 35.946C31.9383 35.9813 32.0617 35.9813 32.1773 35.946L62.0105 26.8303C62.5907 26.653 62.5801 25.828 61.9956 25.6656L32.1624 17.3786C32.0561 17.3491 31.9439 17.3491 31.8376 17.3786Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M31.8376 17.3786L2.0044 25.6656C1.41986 25.828 1.4093 26.653 1.9895 26.8303L31.8227 35.946C31.9383 35.9813 32.0617 35.9813 32.1773 35.946L62.0105 26.8303C62.5907 26.653 62.5801 25.828 61.9956 25.6656L32.1624 17.3786C32.0561 17.3491 31.9439 17.3491 31.8376 17.3786Z"
                            className="base"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Hat.displayName = "Hat";

export default Hat;
