// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Hourglass = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Hourglass} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path className="secondary" d="M58,56H6a2,2,0,0,0,0,4H58a2,2,0,0,0,0-4Z" />
                            <path className="secondary" d="M58,4H6A2,2,0,0,0,6,8H58a2,2,0,0,0,0-4Z" />
                            <path
                                className="base mix-blend-multiply"
                                d="M32,32c-5.22,0-15.65-12.46-19.56-19.6a11.75,11.75,0,0,1-1.32-4.06A12.41,12.41,0,0,1,11.29,4H52.71a12.41,12.41,0,0,1,.17,4.34,11.75,11.75,0,0,1-1.32,4.06C47.5,19.82,36.88,32,32,32Z"
                            />
                            <path
                                className="primary"
                                d="M32.17,27.41c-4,0-12-8.37-15.06-13.17a7.23,7.23,0,0,1-1-2.73,7.36,7.36,0,0,1,.13-2.92H48.11a7.32,7.32,0,0,1,.14,2.91,7.21,7.21,0,0,1-1,2.74C44.1,19.22,35.92,27.41,32.17,27.41Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M32,32c5.22,0,15.65,12.46,19.56,19.6a11.75,11.75,0,0,1,1.32,4.06A12.41,12.41,0,0,1,52.71,60H11.29a12.41,12.41,0,0,1-.17-4.34,11.75,11.75,0,0,1,1.32-4.06C16.5,44.18,27.12,32,32,32Z"
                            />
                            <path
                                className="primary"
                                d="M32.11,47c4.32,0,13,4,16.2,6.3,1.9,1.35.95,2.7.95,2.7H15s-.95-1.35,1-2.7C19.27,50.92,28.07,47,32.11,47Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Hourglass.displayName = "Hourglass";

export default Hourglass;
