// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Integrity = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Integrity} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_2" data-name="Layer 2">
                            <polygon
                                className="secondary"
                                points="54.63 12.57 56.03 10 57.44 12.57 60.02 13.98 57.44 15.39 56.03 17.97 54.63 15.39 52.05 13.98 54.63 12.57"
                            />
                            <polygon
                                className="secondary"
                                points="48.98 5.93 50.03 4 51.09 5.93 53.02 6.98 51.09 8.04 50.03 9.97 48.98 8.04 47.05 6.98 48.98 5.93"
                            />
                            <polygon className="base" points="59 28 32 59 5 28 16 13 48 13 59 28" />
                            <polyline opacity="0.4" className="base mix-blend-multiply" points="18 28 46 28 32 59" />
                            <polygon
                                opacity="0.4"
                                className="base mix-blend-multiply"
                                points="59 28 46 28 40 13 48 13 59 28"
                            />
                            <polygon className="primary " opacity="0.3" points="5 28 18 28 24 13 16 13 5 28" />
                            <polyline opacity="0.1" className="primary" points="5 28 18 28 32 59" />
                            <polyline className="base mix-blend-multiply" points="59 28 46 28 32 59" />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Integrity.displayName = "Integrity";

export default Integrity;
