// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Link = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Link} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="primary"
                                d="M32.22,10.84V1.55a1.55,1.55,0,1,0-3.09,0v9.29a1.55,1.55,0,1,0,3.09,0Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M51.28,18.58H31.67C26.85,18.58,23,23,23,28.39s3.9,9.8,8.72,9.8H51.28c4.82,0,8.72-4.38,8.72-9.8S56.1,18.58,51.28,18.58Zm0,14.71H31.67a4.65,4.65,0,0,1-4.35-4.9,4.65,4.65,0,0,1,4.35-4.91H51.28a4.65,4.65,0,0,1,4.36,4.91,4.72,4.72,0,0,1-1.17,3.35,4.62,4.62,0,0,1-3.19,1.55Z"
                                />
                            </g>
                            <path
                                className="primary"
                                d="M24.75,12.51,18.2,5.94A1.55,1.55,0,0,0,16,8.13l6.55,6.57a1.55,1.55,0,1,0,2.18-2.19Z"
                            />
                            <path
                                className="primary"
                                d="M37.76,14.7,44.3,8.13a1.55,1.55,0,0,0-2.18-2.19l-6.55,6.57a1.56,1.56,0,0,0,0,2.19A1.54,1.54,0,0,0,37.76,14.7Z"
                            />
                            <path
                                className="primary"
                                d="M29.13,53.16v9.29a1.55,1.55,0,1,0,3.09,0V53.16a1.55,1.55,0,1,0-3.09,0Z"
                            />
                            <path
                                className="primary"
                                d="M36.6,51.49l6.55,6.57a1.55,1.55,0,0,0,2.18-2.19L38.78,49.3a1.53,1.53,0,0,0-2.18,0A1.56,1.56,0,0,0,36.6,51.49Z"
                            />
                            <path
                                className="primary"
                                d="M23.59,49.29,17,55.86a1.56,1.56,0,0,0,0,2.19,1.54,1.54,0,0,0,2.19,0l6.54-6.57a1.55,1.55,0,1,0-2.18-2.19Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M32.41,26.31H12.8c-4.82,0-8.72,4.39-8.72,9.81S8,45.93,12.8,45.93H32.41c4.82,0,8.72-4.4,8.72-9.81S37.23,26.31,32.41,26.31Zm0,14.71H12.8a4.65,4.65,0,0,1-4.35-4.89,4.63,4.63,0,0,1,4.35-4.9H32.41a4.59,4.59,0,0,1,3.19,1.54,4.65,4.65,0,0,1,1.17,3.36A4.63,4.63,0,0,1,32.41,41Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Link.displayName = "Link";

export default Link;
