// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Lock = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Lock} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base"
                                d="M55,24H9a2,2,0,0,0-2,2V58a2,2,0,0,0,2,2H55a2,2,0,0,0,2-2V26A2,2,0,0,0,55,24Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M31.27,4A15.27,15.27,0,0,0,17,19.42V31a1,1,0,0,0,1,1h3a1,1,0,0,0,1-1V19.34A10.25,10.25,0,0,1,31.33,9a10,10,0,0,1,9.85,6A10.14,10.14,0,0,1,42,19V31a1,1,0,0,0,1,1h3a1,1,0,0,0,1-1V19A15,15,0,0,0,42.35,8.13a14.7,14.7,0,0,0-5.12-3.2A14.94,14.94,0,0,0,31.27,4Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M37,43.5a5.52,5.52,0,0,0-.75-2.78A5.54,5.54,0,0,0,31.4,38a5.52,5.52,0,0,0-4.75,2.9A5.64,5.64,0,0,0,26,43.7a5.48,5.48,0,0,0,.87,2.75A5.38,5.38,0,0,0,29,48.39V51.5a2.5,2.5,0,1,0,5,0V48.39a5.48,5.48,0,0,0,3-4.89Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Lock.displayName = "Lock";

export default Lock;
