// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Mic = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Mic} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base mix-blend-multiply"
                                d="M37.77,22.67C44.45,30.79,51.26,38.82,57.93,47a3.12,3.12,0,0,1-.2,4.21l-7,6.9a3.07,3.07,0,0,1-2.08.92,3.12,3.12,0,0,1-2.15-.72C38.37,51.58,30.33,44.77,22.2,38.1"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M21.7,39.26a17.68,17.68,0,1,0-6.76-1.32,17.65,17.65,0,0,0,6.76,1.32Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M51.18,49.06,59,56.91A1.48,1.48,0,0,1,59,59h0a1.51,1.51,0,0,1-.49.33,1.53,1.53,0,0,1-1.14,0,1.51,1.51,0,0,1-.49-.33L49,51.15a1.51,1.51,0,0,1-.33-.49,1.53,1.53,0,0,1,0-1.14A1.51,1.51,0,0,1,49,49a1.41,1.41,0,0,1,.5-.33,1.28,1.28,0,0,1,.58-.11,1.43,1.43,0,0,1,.58.12,1.57,1.57,0,0,1,.49.35Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M4.06,31.91l7.85-7.85a1.51,1.51,0,0,1,.49-.33,1.53,1.53,0,0,1,1.14,0,1.51,1.51,0,0,1,.49.33h0a1.51,1.51,0,0,1,.33.49,1.53,1.53,0,0,1,0,1.14,1.51,1.51,0,0,1-.33.49L6.18,34a1.51,1.51,0,0,1-.49.33,1.53,1.53,0,0,1-1.14,0A1.51,1.51,0,0,1,4.06,34h0a1.48,1.48,0,0,1,0-2.09Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M5.06,37.14,21.14,21.06a1.63,1.63,0,0,1,.49-.33,1.56,1.56,0,0,1,1.15,0,1.63,1.63,0,0,1,.49.33,1.52,1.52,0,0,1,0,2.12L7.18,39.27a1.52,1.52,0,0,1-2.12,0h0a1.47,1.47,0,0,1-.44-1.07,1.6,1.6,0,0,1,.11-.57A1.63,1.63,0,0,1,5.06,37.14Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Mic.displayName = "Mic";

export default Mic;
