// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const MobilityCard = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.MobilityCard} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>

                    <rect x="4" y="27" width="28.2927" height="29" rx="3.09872" fill="white" />
                    <rect
                        x="60"
                        y="4"
                        width="56"
                        height="36"
                        rx="1.98142"
                        className="base"
                        transform="rotate(90 60 4)"
                    />
                    <g>
                        <rect
                            x="4"
                            y="27"
                            width="28.2927"
                            height="29"
                            rx="3.09872"
                            className="base mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <rect
                            x="36"
                            y="8"
                            width="10.6667"
                            height="8"
                            rx="2"
                            transform="rotate(90 36 8)"
                            className="secondary mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <path
                            d="M52.2388 49.466C53.1203 49.9749 53.1203 51.2472 52.2388 51.7562L46.2889 55.1914C45.4074 55.7003 44.3055 55.0642 44.3055 54.0463L44.3055 47.1759C44.3055 46.158 45.4074 45.5219 46.2889 46.0308L52.2388 49.466Z"
                            className="secondary mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <path
                            d="M56.2389 49.466C57.1204 49.9749 57.1204 51.2472 56.2389 51.7562L50.2889 55.1914C49.4074 55.7003 48.3056 55.0642 48.3056 54.0463L48.3056 47.1759C48.3056 46.158 49.4074 45.5219 50.2889 46.0308L56.2389 49.466Z"
                            className="tertiary mix-blend-multiply"
                        />
                    </g>
                    <path
                        d="M9 56H13V58C13 59.1046 12.1046 60 11 60V60C9.89543 60 9 59.1046 9 58V56Z"
                        className="base"
                    />
                    <path
                        d="M24 56H28V58C28 59.1046 27.1046 60 26 60V60C24.8954 60 24 59.1046 24 58V56Z"
                        className="base mix-blend-multiply"
                    />
                    <g>
                        <path
                            d="M9 56H13V58C13 59.1046 12.1046 60 11 60V60C9.89543 60 9 59.1046 9 58V56Z"
                            className="base mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <path
                            d="M24 56H28V58C28 59.1046 27.1046 60 26 60V60C24.8954 60 24 59.1046 24 58V56Z"
                            className="base mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <rect
                            x="7.12805"
                            y="29.9121"
                            width="22"
                            height="12.375"
                            rx="1.50595"
                            className="primary mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <rect
                            x="24.1281"
                            y="46"
                            width="5"
                            height="4"
                            rx="1.09524"
                            className="base mix-blend-multiply"
                        />
                    </g>
                    <g>
                        <rect
                            x="7.12805"
                            y="46"
                            width="5"
                            height="4"
                            rx="1.09524"
                            className="base mix-blend-multiply"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

MobilityCard.displayName = "MobilityCard";

export default MobilityCard;
