// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const MobilePlainWithCoin = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.MobilePlainWithCoin} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <rect fill="none" width="64" height="64" />
                            <path
                                className="base"
                                d="M46.5,0h-35A2.64,2.64,0,0,0,9.73.67a2.17,2.17,0,0,0-.54.73A2.26,2.26,0,0,0,9,2.29V61.71a2.26,2.26,0,0,0,.19.89,2.17,2.17,0,0,0,.54.73A2.64,2.64,0,0,0,11.5,64h35a2.64,2.64,0,0,0,1.77-.67,2.17,2.17,0,0,0,.54-.73,2.26,2.26,0,0,0,.19-.89V2.29a2.26,2.26,0,0,0-.19-.89,2.17,2.17,0,0,0-.54-.73A2.64,2.64,0,0,0,46.5,0Z"
                            />
                            <g className="mix-blend-multiply">
                                <path className="base" d="M27,57h3a2,2,0,0,1,0,4H27a2,2,0,0,1,0-4Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M44,47a16,16,0,1,0-11.32-4.69A16,16,0,0,0,44,47Z" />
                            </g>
                            <path
                                fill="white"
                                d="M37.27,22.37h16v1.92h-6.8a6.1,6.1,0,0,1,1.61,3.34h5.15v1.92H48a6,6,0,0,1-1.59,3.13A5.83,5.83,0,0,1,44.6,34l4.89,8.42H47.21L42.64,34.6H37.22v-2h5.12a4.22,4.22,0,0,0,2.95-1.23,4,4,0,0,0,1.07-1.87H37.22V27.63h9.14a4.22,4.22,0,0,0-1.14-2.09,4.12,4.12,0,0,0-2.95-1.21H37.22V22.42Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

MobilePlainWithCoin.displayName = "MobilePlainWithCoin";

export default MobilePlainWithCoin;
