// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const MobileWithGreenTick = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.MobileWithGreenTick} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <g clipPath="url(#clipPath)">
                                <path
                                    className="base"
                                    d="M46.5,0h-35A2.64,2.64,0,0,0,9.73.67a2.17,2.17,0,0,0-.54.73A2.26,2.26,0,0,0,9,2.29V61.71a2.26,2.26,0,0,0,.19.89,2.17,2.17,0,0,0,.54.73A2.64,2.64,0,0,0,11.5,64h35a2.64,2.64,0,0,0,1.77-.67,2.17,2.17,0,0,0,.54-.73,2.26,2.26,0,0,0,.19-.89V2.29a2.26,2.26,0,0,0-.19-.89,2.17,2.17,0,0,0-.54-.73A2.64,2.64,0,0,0,46.5,0Z"
                                />
                                <path
                                    fill="#fff"
                                    opacity="0.4"
                                    d="M43.86,4H14.14a1.14,1.14,0,0,0-.8.33,1.1,1.1,0,0,0-.34.8V54.87a1.1,1.1,0,0,0,.34.8,1.14,1.14,0,0,0,.8.33H43.86a1.14,1.14,0,0,0,.8-.33,1.1,1.1,0,0,0,.34-.8V5.13a1.1,1.1,0,0,0-.34-.8A1.14,1.14,0,0,0,43.86,4Z"
                                />
                                <g className="mix-blend-multiply">
                                    <path className="base" d="M27,57h3a2,2,0,0,1,0,4H27a2,2,0,0,1,0-4Z" />
                                </g>
                                <path className="primary" d="M44,47A16,16,0,1,0,28,31,16,16,0,0,0,44,47Z" />
                                <path
                                    className="secondary"
                                    d="M40.57,32.31a1.52,1.52,0,0,0,.52.36,1.57,1.57,0,0,0,1.25,0,1.52,1.52,0,0,0,.52-.36l6.29-6.58a1.38,1.38,0,0,1,.4-.28,1.18,1.18,0,0,1,1,0,1.15,1.15,0,0,1,.4.28,1.33,1.33,0,0,1,0,1.84l-8.33,8.71a1.38,1.38,0,0,1-.4.28,1.28,1.28,0,0,1-.47.1,1.12,1.12,0,0,1-.48-.1,1.08,1.08,0,0,1-.39-.28l-3.65-3.91a1.34,1.34,0,0,1-.36-.91,1.28,1.28,0,0,1,.76-1.2,1.18,1.18,0,0,1,1,0,1.26,1.26,0,0,1,.4.28Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

MobileWithGreenTick.displayName = "MobileWithGreenTick";

export default MobileWithGreenTick;
