// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const MobileWithOffer = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.MobileWithOffer} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <rect fill="none" width="64" height="64" />
                            <path
                                className="base mix-blend-multiply"
                                d="M45.5,0h-35A2.64,2.64,0,0,0,8.73.67a2.17,2.17,0,0,0-.54.73A2.26,2.26,0,0,0,8,2.29V61.71a2.26,2.26,0,0,0,.19.89,2.17,2.17,0,0,0,.54.73A2.64,2.64,0,0,0,10.5,64h35a2.64,2.64,0,0,0,1.77-.67,2.17,2.17,0,0,0,.54-.73,2.26,2.26,0,0,0,.19-.89V2.29a2.26,2.26,0,0,0-.19-.89,2.17,2.17,0,0,0-.54-.73A2.64,2.64,0,0,0,45.5,0Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M37,6H13c-.57,0-1,.67-1,1.5v9c0,.83.47,1.5,1,1.5H37c.57,0,1-.67,1-1.5v-9C38,6.67,37.53,6,37,6Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M36,38H13c-.55,0-1,.67-1,1.5v9c0,.83.45,1.5,1,1.5H36c.55,0,1-.67,1-1.5v-9C37,38.67,36.55,38,36,38Z"
                                />
                            </g>
                            <path
                                className="secondary"
                                d="M49.51,34h6a1.38,1.38,0,0,0,.66-.17,1.26,1.26,0,0,0,.5-.47l2.9-4.63a1.43,1.43,0,0,0,0-1.46l-2.9-4.63a1.35,1.35,0,0,0-.51-.47,1.29,1.29,0,0,0-.67-.17h-6a1.38,1.38,0,0,0-.66.17,1.26,1.26,0,0,0-.5.47l-2.9,4.63a1.43,1.43,0,0,0,0,1.46l2.9,4.63a1.35,1.35,0,0,0,.51.47A1.29,1.29,0,0,0,49.51,34Z"
                            />
                            <path
                                className="tertiary"
                                d="M49.5,25h6v.72H53A2.26,2.26,0,0,1,53.56,27H55.5v.73H53.56a2.29,2.29,0,0,1-.45,1,2.25,2.25,0,0,1-.85.68l1.84,3.1h-.88l-1.71-3h-2v-.72h1.92a1.6,1.6,0,0,0,1.11-.45,1.74,1.74,0,0,0,.41-.71H49.5v-.71H53a1.53,1.53,0,0,0-.42-.79,1.47,1.47,0,0,0-.51-.34,1.53,1.53,0,0,0-.6-.12h-2Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M43,22H20c-.55,0-1,.67-1,1.5v9c0,.83.45,1.5,1,1.5H43c.55,0,1-.67,1-1.5v-9C44,22.67,43.55,22,43,22Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M30,56H26a2,2,0,0,0,0,4h4a2,2,0,0,0,0-4Z" />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

MobileWithOffer.displayName = "MobileWithOffer";

export default MobileWithOffer;
