// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const MobileWithUpi = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.MobileWithUpi} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M46 4H18C17.4696 4 16.9609 4.21071 16.5858 4.58579C16.2107 4.96086 16 5.46957 16 6V58C16 58.5304 16.2107 59.0391 16.5858 59.4142C16.9609 59.7893 17.4696 60 18 60H46C46.5304 60 47.0391 59.7893 47.4142 59.4142C47.7893 59.0391 48 58.5304 48 58V6C48 5.46957 47.7893 4.96086 47.4142 4.58579C47.0391 4.21071 46.5304 4 46 4V4Z"
                        fill="white"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M46 4H18C17.4696 4 16.9609 4.21071 16.5858 4.58579C16.2107 4.96086 16 5.46957 16 6V58C16 58.5304 16.2107 59.0391 16.5858 59.4142C16.9609 59.7893 17.4696 60 18 60H46C46.5304 60 47.0391 59.7893 47.4142 59.4142C47.7893 59.0391 48 58.5304 48 58V6C48 5.46957 47.7893 4.96086 47.4142 4.58579C47.0391 4.21071 46.5304 4 46 4V4Z"
                            className="primary"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M32 58C32.3956 58 32.7822 57.8827 33.1111 57.6629C33.44 57.4432 33.6964 57.1308 33.8478 56.7654C33.9991 56.3999 34.0387 55.9978 33.9616 55.6098C33.8844 55.2219 33.6939 54.8655 33.4142 54.5858C33.1345 54.3061 32.7781 54.1156 32.3902 54.0384C32.0022 53.9613 31.6001 54.0009 31.2346 54.1522C30.8692 54.3036 30.5568 54.56 30.3371 54.8889C30.1173 55.2178 30 55.6044 30 56C30 56.5304 30.2107 57.0391 30.5858 57.4142C30.9609 57.7893 31.4696 58 32 58Z"
                            className="primary"
                        />
                    </g>
                    <path
                        d="M45 6H19C18.4477 6 18 6.44772 18 7V51C18 51.5523 18.4477 52 19 52H45C45.5523 52 46 51.5523 46 51V7C46 6.44772 45.5523 6 45 6Z"
                        className="base"
                    />
                    <path
                        d="M33.4598 20.08L30.8998 30.08L28.3398 40.08L38.3398 30.08L33.4598 20.08Z"
                        className="secondary"
                    />
                    <path d="M30.12 19L27.58 29L25 39L35 29L30.12 19Z" className="tertiary" />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

MobileWithUpi.displayName = "MobileWithUpi";

export default MobileWithUpi;
