// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const MobileWithCircularArrows = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.MobileWithCircularArrows} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <rect fill="none" width="64" height="64" />
                            <path
                                className="base"
                                d="M49.5,0h-35a2.64,2.64,0,0,0-1.77.67,2.17,2.17,0,0,0-.54.73,2.26,2.26,0,0,0-.19.89V61.71a2.26,2.26,0,0,0,.19.89,2.17,2.17,0,0,0,.54.73A2.64,2.64,0,0,0,14.5,64h35a2.64,2.64,0,0,0,1.77-.67,2.17,2.17,0,0,0,.54-.73,2.26,2.26,0,0,0,.19-.89V2.29a2.26,2.26,0,0,0-.19-.89,2.17,2.17,0,0,0-.54-.73A2.64,2.64,0,0,0,49.5,0Z"
                            />
                            <path
                                fill="#fff"
                                opacity="0.4"
                                d="M46.86,4H17.14a1.14,1.14,0,0,0-.8.33,1.1,1.1,0,0,0-.34.8V54.87a1.1,1.1,0,0,0,.34.8,1.14,1.14,0,0,0,.8.33H46.86a1.14,1.14,0,0,0,.8-.33,1.1,1.1,0,0,0,.34-.8V5.13a1.1,1.1,0,0,0-.34-.8A1.14,1.14,0,0,0,46.86,4Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M59.5,35.71l-4.54-7a.69.69,0,0,0-.23-.22.62.62,0,0,0-.32-.09.56.56,0,0,0-.31.09.54.54,0,0,0-.23.22c-1.53,2.31-3,4.63-4.56,7a.47.47,0,0,0-.12.32.52.52,0,0,0,.12.33.49.49,0,0,0,.2.18.66.66,0,0,0,.27.06h2.41A10.29,10.29,0,0,1,35.34,37C34,35,30.8,36.88,32.15,38.79a13.69,13.69,0,0,0,5.52,4.74,13.93,13.93,0,0,0,14.07-1.25,13.61,13.61,0,0,0,4.56-5.63h2.58a.56.56,0,0,0,.31-.09.58.58,0,0,0,.22-.22.67.67,0,0,0,.08-.3.53.53,0,0,0-.09-.3Z"
                                />
                                <path
                                    className="primary"
                                    d="M55.71,21.81a13.8,13.8,0,0,0-5.58-5,13.54,13.54,0,0,0-14.21,1.41,14.06,14.06,0,0,0-4.54,6H28.11a.58.58,0,0,0-.52.31.57.57,0,0,0-.09.32.71.71,0,0,0,.08.31l4.55,7.25a.64.64,0,0,0,.22.24.61.61,0,0,0,.64,0,.76.76,0,0,0,.23-.24l4.58-7.22a.53.53,0,0,0,.11-.34.5.5,0,0,0-.11-.34.67.67,0,0,0-.21-.2.68.68,0,0,0-.28-.07H35.52a10.4,10.4,0,0,1,3.62-3.51,10.18,10.18,0,0,1,4.75-1.41,10.07,10.07,0,0,1,4.85,1.08,10.31,10.31,0,0,1,3.78,3.28c1.36,1.94,4.56.09,3.19-1.94Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M30,57h3a2,2,0,0,1,0,4H30a2,2,0,0,1,0-4Z" />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

MobileWithCircularArrows.displayName = "MobileWithCircularArrows";

export default MobileWithCircularArrows;
