// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Notepad = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Notepad} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base mix-blend-multiply"
                                d="M52,4H12A3,3,0,0,0,9,7V61a3,3,0,0,0,3,3H52a3,3,0,0,0,3-3V7A3,3,0,0,0,52,4Z"
                            />
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M22,2a2,2,0,0,0-4,0V6a2,2,0,0,0,4,0Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M46,2a2,2,0,0,0-4,0V6a2,2,0,0,0,4,0Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M43.5,38a1.5,1.5,0,0,0,0-3h-23a1.5,1.5,0,0,0,0,3Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M43.5,44a1.5,1.5,0,0,0,0-3h-23a1.5,1.5,0,0,0,0,3Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M35.5,50a1.5,1.5,0,0,0,0-3h-15a1.5,1.5,0,0,0,0,3Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M32,30a6,6,0,1,0-6-6A6,6,0,0,0,32,30Z" />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Notepad.displayName = "Notepad";

export default Notepad;
