// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const PanWithExclamation = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.PanWithExclamation} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M57.9543 48H6.04566C4.92055 48 4 47.088 4 45.9733L4 12.0267C4 10.912 4.92055 10 6.04566 10L57.9543 10C59.0794 10 60 10.912 60 12.0267V45.9733C60 47.088 59.0794 48 57.9543 48Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M55.1512 25H26.8488C26.38 25 26 25.38 26 25.8488V26.1512C26 26.62 26.38 27 26.8488 27H55.1512C55.62 27 56 26.62 56 26.1512V25.8488C56 25.38 55.62 25 55.1512 25Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M47.1512 29H26.8488C26.38 29 26 29.38 26 29.8488V30.1512C26 30.62 26.38 31 26.8488 31H47.1512C47.62 31 48 30.62 48 30.1512V29.8488C48 29.38 47.62 29 47.1512 29Z"
                            className="base"
                        />
                    </g>
                    <path
                        d="M56 19.8707V18C56 15.7909 54.2091 14 52 14C49.7909 14 48 15.7909 48 18V19.8707C48 20.1051 48.19 20.2951 48.4244 20.2951H55.5756C55.81 20.2951 56 20.1051 56 19.8707Z"
                        fill="#FEB452"
                    />
                    <path
                        d="M55.3335 19.8762V18.5931C55.3335 16.7522 53.8412 15.2598 52.0002 15.2598C50.1593 15.2598 48.6669 16.7521 48.6669 18.5931V19.8762C48.6669 20.1079 48.8548 20.2958 49.0865 20.2958H54.9139C55.1456 20.2958 55.3335 20.1079 55.3335 19.8762Z"
                        fill="#F05656"
                    />
                    <path
                        d="M31 14H9C8.44772 14 8 14.4477 8 15C8 15.5523 8.44772 16 9 16H31C31.5523 16 32 15.5523 32 15C32 14.4477 31.5523 14 31 14Z"
                        fill="#F7993B"
                    />
                    <path
                        d="M39 18H9C8.44772 18 8 18.4477 8 19C8 19.5523 8.44772 20 9 20H39C39.5523 20 40 19.5523 40 19C40 18.4477 39.5523 18 39 18Z"
                        fill="#36A168"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            d="M22.1512 25H8.84884C8.38004 25 8 25.38 8 25.8488L8 40.1512C8 40.62 8.38004 41 8.84884 41H22.1512C22.62 41 23 40.62 23 40.1512V25.8488C23 25.38 22.62 25 22.1512 25Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            d="M17.4535 33H13.5465C12.1401 33 11 34.1401 11 35.5465V41H20V35.5465C20 34.1401 18.8599 33 17.4535 33Z"
                            className="base"
                        />
                    </g>
                    <g className="mix-blend-multiply">
                        <circle cx="15.5" cy="29.5" r="2.5" className="base" />
                    </g>
                    <path
                        d="M46.5 58C51.7467 58 56 53.7467 56 48.5C56 43.2533 51.7467 39 46.5 39C41.2533 39 37 43.2533 37 48.5C37 53.7467 41.2533 58 46.5 58Z"
                        className="primary"
                    />
                    <circle cx="46.5" cy="54.5" r="1.5" fill="white" />
                    <rect x="45" y="41" width="3" height="11" rx="1.5" fill="white" />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

PanWithExclamation.displayName = "PanWithExclamation";

export default PanWithExclamation;
