// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const PaperWithCoin = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.PaperWithCoin} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <circle cx="48.6666" cy="39.3333" r="11.3333" fill="white" />

                    <rect x="4" y="4" width="44" height="56" rx="2.66667" className="base" />
                    <g className="mix-blend-multiply">
                        <rect x="9.36572" y="10.7339" width="14.7597" height="2.69338" rx="1.34669" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <rect x="9.36572" y="24.2007" width="22.8105" height="2.69338" rx="1.34669" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <rect x="9.36572" y="17.4668" width="33.5448" height="2.69338" rx="1.34669" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <circle cx="48.6666" cy="39.3333" r="11.3333" className="primary" />
                    </g>
                    <g className="mix-blend-multiply">
                        <path
                            fillRule="evenodd"
                            clipRule="evenodd"
                            d="M44.0215 33.3335H53.3333V34.5289H49.3651C49.8724 35.1006 50.2026 35.8257 50.3106 36.6055H53.3047V37.8009H50.2962C50.1716 38.5336 49.8477 39.2106 49.3651 39.7473C49.056 40.093 48.6891 40.3737 48.2835 40.5749L51.1486 45.7779H49.7805L47.1159 40.9044H44V39.7166H46.9798C47.5132 39.7182 48.032 39.5302 48.4547 39.182C48.8774 38.8339 49.18 38.3454 49.3149 37.7933H44.0215V36.5979H49.3651C49.2515 36.0151 48.9537 35.492 48.5219 35.1166C48.0901 34.7412 47.5506 34.5364 46.9941 34.5366H44V33.3335H44.0215Z"
                            className="base"
                        />
                    </g>
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M44.0215 33.3335H53.3333V34.5289H49.3651C49.8724 35.1006 50.2026 35.8257 50.3106 36.6055H53.3047V37.8009H50.2962C50.1716 38.5336 49.8477 39.2106 49.3651 39.7473C49.056 40.093 48.6891 40.3737 48.2835 40.5749L51.1486 45.7779H49.7805L47.1159 40.9044H44V39.7166H46.9798C47.5132 39.7182 48.032 39.5302 48.4547 39.182C48.8774 38.8339 49.18 38.3454 49.3149 37.7933H44.0215V36.5979H49.3651C49.2515 36.0151 48.9537 35.492 48.5219 35.1166C48.0901 34.7412 47.5506 34.5364 46.9941 34.5366H44V33.3335H44.0215Z"
                        className="secondary"
                    />
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

PaperWithCoin.displayName = "PaperWithCoin";

export default PaperWithCoin;
