// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Payments = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Payments} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        d="M3.60753 45.6046C3.21866 45.2176 3.00003 44.6916 3.00003 44.1429L3.00003 19.8591C3.00003 19.3093 3.21962 18.7822 3.61001 18.395L21.1222 1.02641C21.9285 0.22678 23.2295 0.229461 24.0324 1.0324L52.898 29.898C53.9245 30.9245 53.5971 32.6621 52.2675 33.2447L44.6094 36.6006C44.14 36.8063 43.7641 37.1794 43.5548 37.6471L39.1257 47.5461C38.9201 48.0056 38.5535 48.374 38.0951 48.5819L28.0664 53.1303C27.5995 53.3421 27.2282 53.7202 27.025 54.1909L23.781 61.7046C23.2045 63.0398 21.4641 63.3747 20.4333 62.3489L3.60753 45.6046Z"
                        className="secondary"
                    />
                    <g clipPath="url(#clip0_400_2249)">
                        <rect
                            x="43.8542"
                            y="1.60791"
                            width="4.23392"
                            height="27.52"
                            rx="2.11696"
                            transform="rotate(45 43.8542 1.60791)"
                            fill="white"
                        />
                        <rect
                            x="43.3838"
                            y="14.4395"
                            width="4.23392"
                            height="18.4803"
                            rx="2.11696"
                            transform="rotate(45 43.3838 14.4395)"
                            fill="white"
                        />

                        <path
                            d="M3.6075 45.6046C3.21863 45.2176 3 44.6916 3 44.1429L3 19.8591C3 19.3093 3.21959 18.7822 3.60998 18.395L21.1222 1.02641C21.9284 0.226781 23.2294 0.229461 24.0324 1.0324L52.8979 29.898C53.9244 30.9245 53.5971 32.6621 52.2675 33.2447L44.6093 36.6006C44.14 36.8063 43.764 37.1794 43.5547 37.6471L39.1256 47.5461C38.92 48.0056 38.5535 48.374 38.0951 48.5819L28.0664 53.1303C27.5995 53.3421 27.2282 53.7202 27.025 54.1909L23.7809 61.7046C23.2044 63.0398 21.4641 63.3747 20.4332 62.3489L3.6075 45.6046Z"
                            className="base"
                            fillOpacity="0.25"
                        />
                        <g className="mix-blend-multiply">
                            <path
                                d="M2.93615 32.8722L2.93615 19.9999L14.9361 31.9999L2.93616 43.8722L2.93615 32.8722Z"
                                className="base"
                            />
                        </g>
                        <g className="mix-blend-multiply">
                            <rect
                                x="43.8542"
                                y="1.60791"
                                width="4.23392"
                                height="27.52"
                                rx="2.11696"
                                transform="rotate(45 43.8542 1.60791)"
                                className="primary"
                            ></rect>
                        </g>
                        <g className="mix-blend-multiply">
                            <rect
                                x="43.3838"
                                y="14.4395"
                                width="4.23392"
                                height="18.4803"
                                rx="2.11696"
                                transform="rotate(45 43.3838 14.4395)"
                                className="primary"
                            ></rect>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Payments.displayName = "Payments";

export default Payments;
