// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const PeopleWithCoin = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.PeopleWithCoin} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M49,23a5,5,0,0,0,2.15-.48A5,5,0,0,0,53.91,17,5,5,0,0,0,50,13.1,5,5,0,1,0,49,23Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M60,40.88a1.9,1.9,0,0,1-.11.78,1.8,1.8,0,0,1-.4.68,2,2,0,0,1-.64.47,1.86,1.86,0,0,1-.77.19H38.92a2,2,0,0,1-.77-.19,1.93,1.93,0,0,1-.63-.47,2,2,0,0,1-.41-.68,2.08,2.08,0,0,1-.11-.78V34c0-6.22,4.46-10,10.06-10h2.88C55.54,24,60,27.78,60,34Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M16,14a5,5,0,0,0,2.15-.48,5.07,5.07,0,0,0,1.73-1.35,5.05,5.05,0,0,0,1-4.17A5,5,0,0,0,17,4.1,5,5,0,0,0,11.12,10,5,5,0,0,0,16,14Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M27,31.88a1.9,1.9,0,0,1-.11.78,1.8,1.8,0,0,1-.4.68,2,2,0,0,1-.64.47,1.86,1.86,0,0,1-.77.19H5.92a2,2,0,0,1-.77-.19,1.93,1.93,0,0,1-.63-.47,2,2,0,0,1-.41-.68A2.08,2.08,0,0,1,4,31.88V25c0-6.22,4.46-10,10.06-10h2.88C22.54,15,27,18.78,27,25Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M20,40a5,5,0,0,0,2.15-.48,5.07,5.07,0,0,0,1.73-1.35,5.05,5.05,0,0,0,1-4.17A5,5,0,0,0,21,30.1a5,5,0,0,0-4.16,8.75A5,5,0,0,0,20,40Z"
                                />
                                <path
                                    className="base"
                                    d="M31,57.88a1.9,1.9,0,0,1-.11.78,1.8,1.8,0,0,1-.4.68,2,2,0,0,1-.64.47,1.86,1.86,0,0,1-.77.19H9.92a2,2,0,0,1-.77-.19,1.93,1.93,0,0,1-.63-.47,2,2,0,0,1-.41-.68A2.08,2.08,0,0,1,8,57.88V51c0-6.22,4.46-10,10.06-10h2.88C26.54,41,31,44.78,31,51Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M32,44a11,11,0,1,0-7.78-3.22A11,11,0,0,0,32,44Z" />
                            </g>
                            <path
                                className="secondary"
                                d="M27.38,27.07h11v1.32H33.7a4.16,4.16,0,0,1,1.11,2.29h3.54V32H34.79a4.17,4.17,0,0,1-1.09,2.16,4.27,4.27,0,0,1-1.28.91l3.37,5.75H34.18L31,35.44H27.35V34.13h3.52a2.73,2.73,0,0,0,2.16-1A3.07,3.07,0,0,0,33.64,32H27.38V30.68h6.29a3,3,0,0,0-.59-1.23A2.9,2.9,0,0,0,32,28.63a2.86,2.86,0,0,0-1.08-.22H27.35V27.1Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

PeopleWithCoin.displayName = "PeopleWithCoin";

export default PeopleWithCoin;
