// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const PersonWithSettings = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.PersonWithSettings} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path className="base" d="M25.14,23.91A10,10,0,1,0,18.07,21,10,10,0,0,0,25.14,23.91Z" />
                            <path
                                className="base"
                                d="M24.34,26.81h1.35C36.92,26.81,46,34.24,46,43.4V57.78A2.49,2.49,0,0,1,43.32,60H6.71A2.49,2.49,0,0,1,4,57.78V43.4C4,34.24,13.1,26.81,24.34,26.81Z"
                            />
                            <g className="mix-blend-multiply base">
                                <path className="base" d="M58,25a2,2,0,0,0,0-4H36.33a2,2,0,0,0,0,4Z" />
                            </g>
                            <path
                                className="primary"
                                d="M53.45,18.5H51.89a1.27,1.27,0,0,0-.47.09,1.15,1.15,0,0,0-.66.66,1.27,1.27,0,0,0-.09.47v6.56a1.23,1.23,0,0,0,1.22,1.22h1.56a1.23,1.23,0,0,0,1.22-1.22V19.72a1.23,1.23,0,0,0-1.22-1.22Z"
                            />
                            <g className="mix-blend-multiply base">
                                <path className="base" d="M58,36a2,2,0,0,0,0-4H36.33a2,2,0,0,0,0,4Z" />
                            </g>
                            <path
                                className="secondary"
                                d="M45.45,29.5H43.89a1.27,1.27,0,0,0-.47.09,1.15,1.15,0,0,0-.66.66,1.27,1.27,0,0,0-.09.47v6.56a1.23,1.23,0,0,0,1.22,1.22h1.56a1.23,1.23,0,0,0,1.22-1.22V30.72a1.23,1.23,0,0,0-1.22-1.22Z"
                            />
                            <g className="mix-blend-multiply base">
                                <path className="base" d="M58,47a2,2,0,0,0,0-4H36.33a2,2,0,0,0,0,4Z" />
                            </g>
                            <path
                                className="primary"
                                d="M54.45,40.5H52.89a1.27,1.27,0,0,0-.47.09,1.15,1.15,0,0,0-.66.66,1.27,1.27,0,0,0-.09.47v6.56a1.23,1.23,0,0,0,1.22,1.22h1.56a1.23,1.23,0,0,0,1.22-1.22V41.72a1.23,1.23,0,0,0-1.22-1.22Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

PersonWithSettings.displayName = "PersonWithSettings";

export default PersonWithSettings;
