// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const PersonWithCard = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.PersonWithCard} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <g clipPath="url(#clipPath)">
                                <path
                                    className="base"
                                    d="M59.77,54.23H4.23A4.73,4.73,0,0,1,.94,52.67,4.82,4.82,0,0,1,0,51.07a4.62,4.62,0,0,1-.26-1.84V12.85A4.62,4.62,0,0,1,0,11a4.82,4.82,0,0,1,1-1.6A4.73,4.73,0,0,1,4.23,7.85H59.77a4.64,4.64,0,0,1,1.8.45,4.69,4.69,0,0,1,1.49,1.11A4.82,4.82,0,0,1,64,11a4.62,4.62,0,0,1,.26,1.84V49.26A4.62,4.62,0,0,1,64,51.1a4.82,4.82,0,0,1-1,1.6,4.69,4.69,0,0,1-1.49,1.11,4.64,4.64,0,0,1-1.8.45Z"
                                />
                                <g className="mix-blend-multiply">
                                    <path
                                        className="primary"
                                        d="M19.61,25.59a7.13,7.13,0,0,0,7-8.53,7.14,7.14,0,1,0-7,8.53Z"
                                    />
                                </g>
                                <g className="mix-blend-multiply">
                                    <path
                                        className="primary"
                                        d="M32.14,57.88a1.89,1.89,0,0,1-.13.78,1.83,1.83,0,0,1-.43.67,2.28,2.28,0,0,1-1.49.67H9.17a2.35,2.35,0,0,1-1.52-.66,1.83,1.83,0,0,1-.43-.67,1.94,1.94,0,0,1-.14-.79V38.2c0-6.26,4.85-10.06,11-10.06h3.14c6.11,0,11,3.8,11,10.06Z"
                                    />
                                </g>
                                <g className="mix-blend-multiply">
                                    <path
                                        className="base"
                                        d="M56.62,16.4h-24a1.5,1.5,0,0,0,0,3h24a1.5,1.5,0,0,0,0-3Z"
                                    />
                                </g>
                                <g className="mix-blend-multiply">
                                    <path
                                        className="base"
                                        d="M47.62,22.4h-15a1.56,1.56,0,0,0-.57.11,1.54,1.54,0,0,0-.82.82,1.53,1.53,0,0,0,0,1.14,1.54,1.54,0,0,0,.82.82,1.56,1.56,0,0,0,.57.11h15a1.5,1.5,0,0,0,0-3Z"
                                    />
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

PersonWithCard.displayName = "PersonWithCard";

export default PersonWithCard;
