// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Receipt = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Receipt} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base"
                                d="M25.09,4.71,9.71,20.09a2.76,2.76,0,0,0-.53.78A2.48,2.48,0,0,0,9,21.8V58l7.2-2.4,9.6,4.8,12-4.8,10.8,4.8L57,58V6.4a2.39,2.39,0,0,0-.18-.92,2.39,2.39,0,0,0-1.3-1.3A2.39,2.39,0,0,0,54.6,4H26.8a2.48,2.48,0,0,0-.93.18A2.76,2.76,0,0,0,25.09,4.71Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M24.6,5.2V17.55a1.94,1.94,0,0,1-.14.79,2.09,2.09,0,0,1-1.12,1.12,1.94,1.94,0,0,1-.79.14H10.2Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M41.6,30H6.4a1.5,1.5,0,0,0,0,3H41.6a1.5,1.5,0,0,0,0-3Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M32.58,37H6.42a1.5,1.5,0,0,0,0,3H32.58a1.5,1.5,0,0,0,0-3Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Receipt.displayName = "Receipt";

export default Receipt;
