// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const RingWithDiamond = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.RingWithDiamond} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M31 60C43.7025 60 54 49.7025 54 37C54 24.2975 43.7025 14 31 14C18.2975 14 8 24.2975 8 37C8 49.7025 18.2975 60 31 60ZM31 54C40.3888 54 48 46.3888 48 37C48 27.6112 40.3888 20 31 20C21.6112 20 14 27.6112 14 37C14 46.3888 21.6112 54 31 54Z"
                        className="base"
                    />
                    <g className="mix-blend-multiply">
                        <path
                            fillRule="evenodd"
                            clipRule="evenodd"
                            d="M31 60C43.7025 60 54 49.7025 54 37C54 24.2975 43.7025 14 31 14C18.2975 14 8 24.2975 8 37C8 49.7025 18.2975 60 31 60ZM31 54C40.3888 54 48 46.3888 48 37C48 27.6112 40.3888 20 31 20C21.6112 20 14 27.6112 14 37C14 46.3888 21.6112 54 31 54Z"
                            className="base"
                        />
                    </g>
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M31 58C43.7025 58 54 47.7025 54 35C54 22.2975 43.7025 12 31 12C18.2975 12 8 22.2975 8 35C8 47.7025 18.2975 58 31 58ZM31 52C40.3888 52 48 44.3888 48 35C48 25.6112 40.3888 18 31 18C21.6112 18 14 25.6112 14 35C14 44.3888 21.6112 52 31 52Z"
                        className="base"
                    />
                    <path d="M44 10.6667L32 24.4444L20 10.6667L24.8889 4H39.1111L44 10.6667Z" className="primary" />
                    <g className="mix-blend-multiply" opacity="0.4">
                        <path d="M25.7778 10.667H38.2223L32 24.4448" className="primary" />
                    </g>
                    <g className="mix-blend-multiply" opacity="0.4">
                        <path d="M44 10.6667H38.2222L35.5555 4H39.1111L44 10.6667Z" className="primary" />
                    </g>
                    <path opacity="0.3" d="M20 10.6667H25.7778L28.4444 4H24.8889L20 10.6667Z" fill="white" />
                    <path opacity="0.1" d="M20 10.667H25.7778L32 24.4448" fill="white" />
                    <g className="mix-blend-multiply">
                        <path d="M44 10.667H38.2222L32 24.4448" className="primary" />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

RingWithDiamond.displayName = "RingWithDiamond";

export default RingWithDiamond;
