// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Stopwatch = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Stopwatch} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="secondary"
                                d="M23.6,16.13l-3.22-3.82a2,2,0,0,0-2.82-.24L14.5,14.65a2,2,0,0,0-.23,2.82l3.22,3.82a2,2,0,0,0,2.82.24L23.37,19A2,2,0,0,0,23.6,16.13Z"
                            />
                            <path
                                className="secondary"
                                d="M49.46,12.15l-3.53,3.53a2,2,0,0,0,0,2.83l2.83,2.83a2,2,0,0,0,2.82,0l3.54-3.54a2,2,0,0,0,0-2.82l-2.83-2.83A2,2,0,0,0,49.46,12.15Z"
                            />
                            <path
                                className="base"
                                d="M34.71,60A25.29,25.29,0,1,0,9.42,34.71,25.29,25.29,0,0,0,34.71,60Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="secondary"
                                    d="M34.71,39a4.28,4.28,0,0,0,4.19-5.1,4.27,4.27,0,0,0-5.82-3.12,4.36,4.36,0,0,0-1.92,1.58A4.27,4.27,0,0,0,34.71,39Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M34.71,9.42a25.19,25.19,0,1,0,9.68,1.92A25.19,25.19,0,0,0,34.71,9.42Zm0,46.73a21.45,21.45,0,1,1,15.16-6.28A21.41,21.41,0,0,1,34.71,56.15Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M42.71,8a2,2,0,0,0,1.41-3.41A2,2,0,0,0,42.71,4h-16A2,2,0,0,0,25.3,7.41,2,2,0,0,0,26.71,8Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M10.64,49a1.29,1.29,0,0,0,1-.44,1.6,1.6,0,0,0,0-2.12,1.29,1.29,0,0,0-1-.44H5.12a1.29,1.29,0,0,0-1,.44,1.6,1.6,0,0,0,0,2.12,1.29,1.29,0,0,0,1,.44Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M20.39,55a1.67,1.67,0,0,0,1.14-.44,1.43,1.43,0,0,0,0-2.12A1.67,1.67,0,0,0,20.39,52H8.16A1.67,1.67,0,0,0,7,52.44a1.43,1.43,0,0,0,0,2.12A1.67,1.67,0,0,0,8.16,55Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M36,19V17c0-1.1-.67-2-1.5-2s-1.5.9-1.5,2v2c0,1.1.67,2,1.5,2S36,20.1,36,19Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="secondary" d="M36.66,34.07v-8.6a2,2,0,0,0-4,0v8.6a2,2,0,0,0,4,0Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M36.06,52.8v-2c0-1.1-.67-2-1.5-2s-1.5.9-1.5,2v2c0,1.1.67,2,1.5,2S36.06,53.9,36.06,52.8Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M18.71,33h-2c-1.1,0-2,.67-2,1.5s.9,1.5,2,1.5h2c1.1,0,2-.67,2-1.5S19.81,33,18.71,33Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M52.71,33h-2c-1.1,0-2,.67-2,1.5s.9,1.5,2,1.5h2c1.1,0,2-.67,2-1.5S53.81,33,52.71,33Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Stopwatch.displayName = "Stopwatch";

export default Stopwatch;
