// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Tenacity = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Tenacity} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_2" data-name="Layer 2">
                            <circle className="base mix-blend-multiply" opacity="0.5" cx="32" cy="32" r="28" />
                            <path
                                className="base"
                                d="M32,4A28,28,0,1,0,60,32,28,28,0,0,0,32,4Zm0,51A23,23,0,1,1,55,32,23,23,0,0,1,32,55Z"
                            />
                            <circle className="base" cx="32" cy="32" r="5" />
                            <path
                                className="base"
                                d="M32,14.5A17.5,17.5,0,1,0,49.5,32,17.51,17.51,0,0,0,32,14.5Zm0,30A12.5,12.5,0,1,1,44.5,32,12.5,12.5,0,0,1,32,44.5Z"
                            />
                            <polygon
                                className="secondary"
                                points="53.09 12.75 55.57 13.54 60.54 8.77 58.05 7.98 53.09 12.75"
                            />
                            <polygon
                                className="secondary"
                                points="51.44 11.16 50.61 8.77 55.57 4 56.4 6.39 51.44 11.16"
                            />
                            <path
                                className="primary"
                                d="M31.34,32.06h0a1.21,1.21,0,0,0,1.66,0L57.82,8.2a1.11,1.11,0,0,0,0-1.59h0a1.21,1.21,0,0,0-1.66,0L31.34,30.47A1.11,1.11,0,0,0,31.34,32.06Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Tenacity.displayName = "Tenacity";

export default Tenacity;
