// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Ticket = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Ticket} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <rect fill="none" width="64" height="64" />
                            <path
                                className="base mix-blend-multiply"
                                d="M11,19.78H50.93V61.67A2.45,2.45,0,0,1,48.58,64h-7c-1.22,0-2-1.19-2.34-2.33-1-3.68-4.11-5.76-8.22-5.82s-8.43,2.17-9.4,5.82C21.27,62.8,20.44,64,19.22,64H13.35a2.47,2.47,0,0,1-1.62-.72A2.51,2.51,0,0,1,11,61.67Z"
                            />
                            <g className="mix-blend-multiply">
                                <path className="base" d="M31,47a1,1,0,0,0-2,0V59a1,1,0,0,0,2,0Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M36,32.5a1.5,1.5,0,0,0-3,0v26a1.5,1.5,0,0,0,3,0Z" />
                            </g>
                            <path
                                className="primary"
                                d="M11.61,17.12l38.72,4.42L52,6.54A2.47,2.47,0,0,0,50,4l-6.83-.78C42,3,41.07,4.19,40.66,5.24c-1.39,3.49-5.82,5.23-9.8,4.76s-6.77-3-7.34-6.74a2.85,2.85,0,0,0-.59-1.63A2.77,2.77,0,0,0,21.51.68L15.68,0a2.11,2.11,0,0,0-.83,0,2.15,2.15,0,0,0-.74.37,2.06,2.06,0,0,0-.54.63,2.18,2.18,0,0,0-.27.79Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Ticket.displayName = "Ticket";

export default Ticket;
