// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const TV = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.TV} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <rect x="60" y="11" width="38" height="56" rx="2.66667" transform="rotate(90 60 11)" fill="white" />

                    <g className="mix-blend-multiply">
                        <rect
                            x="45"
                            y="51"
                            width="2"
                            height="26"
                            rx="1"
                            transform="rotate(90 45 51)"
                            className="base"
                        />
                    </g>
                    <rect x="45" y="51" width="2" height="26" rx="1" transform="rotate(90 45 51)" className="primary" />
                    <g className="mix-blend-multiply">
                        <rect x="34" y="51" width="4" height="2" transform="rotate(-180 34 51)" className="base" />
                    </g>
                    <g className="mix-blend-multiply">
                        <rect x="34" y="52" width="4" height="3" transform="rotate(-180 34 52)" className="primary" />
                    </g>
                    <g className="mix-blend-multiply">
                        <rect
                            x="60"
                            y="11"
                            width="38"
                            height="56"
                            rx="2.66667"
                            transform="rotate(90 60 11)"
                            className="base"
                        />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

TV.displayName = "TV";

export default TV;
