// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const UPIQR = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.UPIQR} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                >
                    <defs></defs>
                    <rect x="4" y="29" width="56" height="6" rx="2" fill="white" />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M34 33C34.5523 33 35 33.4477 35 34V40C35 40.5523 34.5523 41 34 41C33.4477 41 33 40.5523 33 40V34C33 33.4477 33.4477 33 34 33Z"
                        className="primary"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M18 18C16.8954 18 16 18.8954 16 20V26C16 27.1046 16.8954 28 18 28H24C25.1046 28 26 27.1046 26 26V20C26 18.8954 25.1046 18 24 18H18ZM15 15C13.8954 15 13 15.8954 13 17V29C13 30.1046 13.8954 31 15 31H27C28.1046 31 29 30.1046 29 29V17C29 15.8954 28.1046 15 27 15H15Z"
                        className="base"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M18 36C16.8954 36 16 36.8954 16 38V44C16 45.1046 16.8954 46 18 46H24C25.1046 46 26 45.1046 26 44V38C26 36.8954 25.1046 36 24 36H18ZM15 33C13.8954 33 13 33.8954 13 35V47C13 48.1046 13.8954 49 15 49H27C28.1046 49 29 48.1046 29 47V35C29 33.8954 28.1046 33 27 33H15Z"
                        className="base"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M38 18C36.8954 18 36 18.8954 36 20V26C36 27.1046 36.8954 28 38 28H44C45.1046 28 46 27.1046 46 26V20C46 18.8954 45.1046 18 44 18H38ZM35 15C33.8954 15 33 15.8954 33 17V29C33 30.1046 33.8954 31 35 31H47C48.1046 31 49 30.1046 49 29V17C49 15.8954 48.1046 15 47 15H35Z"
                        className="base"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M16 5.5C16 4.67157 15.3284 4 14.5 4H6C4.89543 4 4 4.89543 4 6V14.5C4 15.3284 4.67157 16 5.5 16V16C6.32843 16 7 15.3284 7 14.5V9C7 7.89543 7.89543 7 9 7H14.5C15.3284 7 16 6.32843 16 5.5V5.5Z"
                        className="primary"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M5.5 48C4.67157 48 4 48.6716 4 49.5L4 58C4 59.1046 4.89543 60 6 60H14.5C15.3284 60 16 59.3284 16 58.5V58.5C16 57.6716 15.3284 57 14.5 57H9C7.89543 57 7 56.1046 7 55V49.5C7 48.6716 6.32843 48 5.5 48V48Z"
                        className="primary"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M58.5 16C59.3284 16 60 15.3284 60 14.5V6C60 4.89543 59.1046 4 58 4L49.5 4C48.6716 4 48 4.67157 48 5.5V5.5C48 6.32843 48.6716 7 49.5 7H55C56.1046 7 57 7.89543 57 9V14.5C57 15.3284 57.6716 16 58.5 16V16Z"
                        className="primary"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M48 58.5C48 59.3284 48.6716 60 49.5 60H58C59.1046 60 60 59.1046 60 58V49.5C60 48.6716 59.3284 48 58.5 48V48C57.6716 48 57 48.6716 57 49.5V55C57 56.1046 56.1046 57 55 57H49.5C48.6716 57 48 57.6716 48 58.5V58.5Z"
                        className="primary"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M38 33C38.5523 33 39 33.4477 39 34V37H42.5C43.0523 37 43.5 37.4477 43.5 38C43.5 38.5523 43.0523 39 42.5 39H39V47C39 48 38 49 37 49H34C33.4477 49 33 48.5523 33 48C33 47.4477 33.4477 47 34 47H36C36.5523 47 37 46.5523 37 46V34C37 33.4477 37.4477 33 38 33Z"
                        className="base"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M42 34C42 33.4477 42.4477 33 43 33H47C48 33 49 34 49 35V38C49 38.5523 48.5523 39 48 39C47.4477 39 47 38.5523 47 38V36C47 35.4477 46.5523 35 46 35H43C42.4477 35 42 34.5523 42 34Z"
                        className="base"
                    />
                    <path
                        fillRule="evenodd"
                        clipRule="evenodd"
                        d="M48 43C48.5523 43 49 43.4477 49 44V47C49 48 48 49 47 49H43C42.4477 49 42 48.5523 42 48C42 47.4477 42.4477 47 43 47H46C46.5523 47 47 46.5523 47 46V44C47 43.4477 47.4477 43 48 43Z"
                        className="base"
                    />
                    <rect x="41" y="41" width="4" height="4" rx="1" className="primary" />
                    <g className="mix-blend-multiply">
                        <rect x="4" y="29" width="56" height="6" rx="2" className="primary" />
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

UPIQR.displayName = "UPIQR";

export default UPIQR;
