// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const Wave = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.Wave} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path className="primary" d="M45,27a9,9,0,1,0-9-9A9,9,0,0,0,45,27Z" />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M4,57H60V38.86H59c-10.93,0-15-5.86-17-17S31.84,7,23,7,7,13,7,21.86v1a5.81,5.81,0,0,1,6-5.57,6,6,0,0,1,6,5.57C19,25,19,31,6,31H4Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="secondary" d="M60,52H4v5H60Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="secondary"
                                    d="M7,31c6.63,0,18,0,18-10C25,10,7,6,7,21.86v1a5.81,5.81,0,0,1,6-5.57,6,6,0,0,1,6,5.57C19,25,19,31,6,31"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

Wave.displayName = "Wave";

export default Wave;
