// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const WindowWithUpArrow = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.WindowWithUpArrow} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <rect fill="none" width="64" height="64" />
                            <path
                                className="base"
                                d="M61.71,56H2.29a2.21,2.21,0,0,1-1.62-.7A2.49,2.49,0,0,1,0,53.6V10.4A2.49,2.49,0,0,1,.67,8.7,2.21,2.21,0,0,1,2.29,8H61.71a2.21,2.21,0,0,1,1.62.7A2.49,2.49,0,0,1,64,10.4V53.6a2.49,2.49,0,0,1-.67,1.7,2.21,2.21,0,0,1-1.62.7Z"
                            />
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M5.5,12.89a1.53,1.53,0,0,0,1.28-.73A1.39,1.39,0,0,0,7,11.53a1.44,1.44,0,0,0-.08-.65,1.47,1.47,0,0,0-.35-.55,1.45,1.45,0,0,0-.77-.41,1.49,1.49,0,0,0-.86.08,1.66,1.66,0,0,0-.68.55,1.56,1.56,0,0,0-.25.84,1.5,1.5,0,0,0,1.5,1.5Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M10.5,12.89a1.53,1.53,0,0,0,1.28-.73,1.39,1.39,0,0,0,.21-.63,1.44,1.44,0,0,0-.08-.65,1.47,1.47,0,0,0-.35-.55,1.45,1.45,0,0,0-.77-.41,1.49,1.49,0,0,0-.86.08,1.66,1.66,0,0,0-.68.55,1.56,1.56,0,0,0-.25.84,1.5,1.5,0,0,0,1.5,1.5Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M15.5,12.89a1.53,1.53,0,0,0,1.28-.73,1.39,1.39,0,0,0,.21-.63,1.44,1.44,0,0,0-.08-.65,1.47,1.47,0,0,0-.35-.55,1.45,1.45,0,0,0-.77-.41,1.49,1.49,0,0,0-.86.08,1.66,1.66,0,0,0-.68.55,1.56,1.56,0,0,0-.25.84,1.5,1.5,0,0,0,1.5,1.5Z"
                                />
                            </g>
                            <path
                                fill="#fff"
                                opacity="0.4"
                                d="M57.93,51H6.07A2.31,2.31,0,0,1,4,48.52v-31A2.3,2.3,0,0,1,6.07,15H57.93A2.31,2.31,0,0,1,60,17.48v31A2.3,2.3,0,0,1,57.93,51Z"
                            />
                            <g className="mix-blend-multiply">
                                <path className="primary" d="M53,25l-6,8h3V59a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V33h3Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M45,36H41a1,1,0,0,0-1,1V59a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V37A1,1,0,0,0,45,36Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="base"
                                    d="M35,42H31a1,1,0,0,0-1,1V59a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V43A1,1,0,0,0,35,42Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

WindowWithUpArrow.displayName = "WindowWithUpArrow";

export default WindowWithUpArrow;
