// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const WindowWithMobile = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.WindowWithMobile} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base mix-blend-multiply"
                                d="M62,12H2a2,2,0,0,0-2,2V58a2,2,0,0,0,2,2H62a2,2,0,0,0,2-2V14A2,2,0,0,0,62,12Z"
                            />
                            <path
                                fill="#fff"
                                opacity="0.4"
                                d="M59,21H5a1,1,0,0,0-1,1V55a1,1,0,0,0,1,1H59a1,1,0,0,0,1-1V22A1,1,0,0,0,59,21Z"
                            />
                            <g className="mix-blend-multiply">
                                <path className="base" d="M5.5,18A1.5,1.5,0,1,0,4,16.5,1.5,1.5,0,0,0,5.5,18Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M10.5,18A1.5,1.5,0,1,0,9,16.5,1.5,1.5,0,0,0,10.5,18Z" />
                            </g>
                            <g className="mix-blend-multiply">
                                <path className="base" d="M15.5,18A1.5,1.5,0,1,0,14,16.5,1.5,1.5,0,0,0,15.5,18Z" />
                            </g>
                            <path className="primary" d="M9,32H31a1,1,0,0,1,1,1V56H8V33a1,1,0,0,1,1-1Z" />
                            <path
                                className="secondary"
                                d="M31,26H9a1,1,0,0,0-1,1v2a1,1,0,0,0,1,1H31a1,1,0,0,0,1-1V27A1,1,0,0,0,31,26Z"
                            />
                            <path
                                className="tertiary"
                                d="M62,4H42a2,2,0,0,0-2,2V42a2,2,0,0,0,2,2H62a2,2,0,0,0,2-2V6A2,2,0,0,0,62,4Z"
                            />
                            <path
                                fill="#fff"
                                opacity="0.4"
                                d="M61,6H43a1,1,0,0,0-1,1V37a1,1,0,0,0,1,1H61a1,1,0,0,0,1-1V7A1,1,0,0,0,61,6Z"
                            />
                            <path className="primary" d="M45,22h6a1,1,0,0,1,1,1V38H44V23a1,1,0,0,1,1-1Z" />
                            <path
                                className="secondary"
                                d="M51.5,19h-7a.5.5,0,0,0-.5.5v1a.5.5,0,0,0,.5.5h7a.5.5,0,0,0,.5-.5v-1A.5.5,0,0,0,51.5,19Z"
                            />
                            <g className="mix-blend-multiply">
                                <path className="base" d="M53,40H51a1,1,0,0,0,0,2h2a1,1,0,0,0,0-2Z" />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

WindowWithMobile.displayName = "WindowWithMobile";

export default WindowWithMobile;
