// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const WindowWithLightning = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.WindowWithLightning} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base"
                                d="M61.71,56H2.29a2.25,2.25,0,0,1-.88-.19,2.23,2.23,0,0,1-.74-.51A2.49,2.49,0,0,1,0,53.6V10.4A2.49,2.49,0,0,1,.67,8.7,2.21,2.21,0,0,1,2.29,8H61.71a2.21,2.21,0,0,1,1.62.7A2.49,2.49,0,0,1,64,10.4V53.6a2.49,2.49,0,0,1-.67,1.7,2.32,2.32,0,0,1-1.62.7Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M5.52,15.11a1.64,1.64,0,0,0,.83-.25,1.52,1.52,0,0,0,.55-.68,1.41,1.41,0,0,0,.1-.86,1.43,1.43,0,0,0-.4-.78A1.5,1.5,0,0,0,5,12.21a1.55,1.55,0,0,0-.67.57,1.36,1.36,0,0,0-.25.83,1.6,1.6,0,0,0,.11.57,1.63,1.63,0,0,0,.33.49A1.54,1.54,0,0,0,5.52,15.11Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M10.52,15.11a1.64,1.64,0,0,0,.83-.25,1.52,1.52,0,0,0,.55-.68,1.41,1.41,0,0,0,.09-.86,1.43,1.43,0,0,0-.4-.78,1.5,1.5,0,0,0-1.65-.33,1.55,1.55,0,0,0-.67.57,1.36,1.36,0,0,0-.25.83,1.6,1.6,0,0,0,.11.57,1.63,1.63,0,0,0,.33.49A1.5,1.5,0,0,0,10.52,15.11Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M15.52,15.11a1.64,1.64,0,0,0,.83-.25,1.52,1.52,0,0,0,.55-.68,1.41,1.41,0,0,0,.09-.86,1.43,1.43,0,0,0-.4-.78,1.5,1.5,0,0,0-1.65-.33,1.55,1.55,0,0,0-.67.57,1.36,1.36,0,0,0-.25.83,1.6,1.6,0,0,0,.11.57,1.63,1.63,0,0,0,.33.49A1.5,1.5,0,0,0,15.52,15.11Z"
                            />
                            <g className="isolate">
                                <path
                                    fill="#fff"
                                    opacity="0.4"
                                    d="M58.68,18.11H5.29a1.46,1.46,0,0,0-.51.12,1.38,1.38,0,0,0-.43.32,1.29,1.29,0,0,0-.27.45,1.37,1.37,0,0,0-.08.53v32a1.25,1.25,0,0,0,.06.54,1.31,1.31,0,0,0,.27.47,1.37,1.37,0,0,0,.43.33,1.42,1.42,0,0,0,.53.13H58.68a1.63,1.63,0,0,0,.53-.12,1.55,1.55,0,0,0,.44-.32,1.31,1.31,0,0,0,.28-.47,1.36,1.36,0,0,0,.07-.53v-32a1.39,1.39,0,0,0-.07-.54,1.18,1.18,0,0,0-.28-.47,1.16,1.16,0,0,0-.44-.32A1.24,1.24,0,0,0,58.68,18.11Z"
                                />
                            </g>
                            <path className="tertiary" d="M29,22H9a1,1,0,0,0,0,2H29a1,1,0,0,0,0-2Z" />
                            <path className="primary" d="M19,26H9a1,1,0,0,0,0,2H19a1,1,0,0,0,0-2Z" />
                            <path className="secondary" d="M12,30H9a1,1,0,0,0,0,2h3a1,1,0,0,0,0-2Z" />
                            <path className="primary" d="M32,30H16a1,1,0,0,0,0,2H32a1,1,0,0,0,0-2Z" />
                            <path className="tertiary" d="M25,34H9a1,1,0,0,0,0,2H25a1,1,0,0,0,0-2Z" />
                            <path className="secondary" d="M40,30H36a1,1,0,0,0,0,2h4a1,1,0,0,0,0-2Z" />
                            <path className="secondary" d="M33,26H23a1,1,0,0,0,0,2H33a1,1,0,0,0,0-2Z" />
                            <path
                                className="primary mix-blend-multiply"
                                d="M52.17,4H44.65a1,1,0,0,0-.65.22,1,1,0,0,0-.35.59L41,18.54A1.08,1.08,0,0,0,41,19a.92.92,0,0,0,.21.39.85.85,0,0,0,.35.27,1,1,0,0,0,.43.09h8.27L48,29.88a.13.13,0,0,0,0,.06s0,0,.05,0h.07a.1.1,0,0,0,0,0l7.73-13.46A1,1,0,0,0,56,16a1,1,0,0,0-.15-.5.94.94,0,0,0-.38-.36A.92.92,0,0,0,55,15H49l4.14-9.6a1,1,0,0,0,.08-.5,1.11,1.11,0,0,0-.17-.47,1,1,0,0,0-.39-.33,1,1,0,0,0-.49-.1Z"
                            />
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

WindowWithLightning.displayName = "WindowWithLightning";

export default WindowWithLightning;
