// GENERATED BY /script/build.js
// DO NOT EDIT MANUALLY

import * as React from "react";
import { PictogramIconProps } from "../../types";
import { SVGPictogramWrapper } from "../../styles";
import { PictogramsNames } from "../../iconsNames";

export const WindowWithBarGraph = React.forwardRef<SVGSVGElement, PictogramIconProps>(
    ({ width = 64, height = 64, ...props }, forwardedRef) => {
        return (
            <SVGPictogramWrapper icon={PictogramsNames.WindowWithBarGraph} {...props}>
                <svg
                    width={width}
                    height={height}
                    ref={forwardedRef}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 64 64"
                >
                    <defs></defs>
                    <g className="isolate">
                        <g id="Layer_1" data-name="Layer 1">
                            <path
                                className="base"
                                d="M61.71,56H2.29a2.21,2.21,0,0,1-1.62-.7A2.49,2.49,0,0,1,0,53.6V10.4A2.49,2.49,0,0,1,.67,8.7,2.21,2.21,0,0,1,2.29,8H61.71a2.21,2.21,0,0,1,1.62.7A2.49,2.49,0,0,1,64,10.4V53.6a2.49,2.49,0,0,1-.67,1.7,2.21,2.21,0,0,1-1.62.7Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M5.52,14.11a1.55,1.55,0,0,0,.83-.25,1.47,1.47,0,0,0,.55-.68,1.41,1.41,0,0,0,.1-.86,1.47,1.47,0,0,0-.4-.78,1.53,1.53,0,0,0-.78-.42,1.62,1.62,0,0,0-.87.09,1.55,1.55,0,0,0-.67.57,1.36,1.36,0,0,0-.25.83,1.66,1.66,0,0,0,.11.58,1.58,1.58,0,0,0,.33.48A1.49,1.49,0,0,0,5.52,14.11Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M10.52,14.11a1.55,1.55,0,0,0,.83-.25,1.47,1.47,0,0,0,.55-.68,1.41,1.41,0,0,0,.09-.86,1.47,1.47,0,0,0-.4-.78,1.53,1.53,0,0,0-.78-.42,1.62,1.62,0,0,0-.87.09,1.55,1.55,0,0,0-.67.57,1.36,1.36,0,0,0-.25.83,1.66,1.66,0,0,0,.11.58,1.58,1.58,0,0,0,.33.48A1.5,1.5,0,0,0,10.52,14.11Z"
                            />
                            <path
                                className="base mix-blend-multiply"
                                d="M15.52,14.11a1.55,1.55,0,0,0,.83-.25,1.47,1.47,0,0,0,.55-.68,1.41,1.41,0,0,0,.09-.86,1.47,1.47,0,0,0-.4-.78,1.53,1.53,0,0,0-.78-.42,1.62,1.62,0,0,0-.87.09,1.55,1.55,0,0,0-.67.57,1.36,1.36,0,0,0-.25.83,1.66,1.66,0,0,0,.11.58,1.58,1.58,0,0,0,.33.48A1.5,1.5,0,0,0,15.52,14.11Z"
                            />
                            <g>
                                <path
                                    fill="#fff"
                                    opacity="0.4"
                                    d="M58.68,17.11H5.29a1.28,1.28,0,0,0-.51.13,1.22,1.22,0,0,0-.43.31,1.33,1.33,0,0,0-.27.46,1.29,1.29,0,0,0-.08.52v32a1.24,1.24,0,0,0,.06.54,1.16,1.16,0,0,0,.27.47,1.37,1.37,0,0,0,.43.33,1.42,1.42,0,0,0,.53.13H58.68a1.35,1.35,0,0,0,1-.44,1.36,1.36,0,0,0,.28-.46,1.44,1.44,0,0,0,.07-.54v-32a1.41,1.41,0,0,0-.07-.54,1.34,1.34,0,0,0-.28-.47,1.43,1.43,0,0,0-.44-.32A1.24,1.24,0,0,0,58.68,17.11Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="primary"
                                    d="M54,27H50a1,1,0,0,0-1,1V58a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V28A1,1,0,0,0,54,27Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="secondary"
                                    d="M44,35H40a1,1,0,0,0-1,1V58a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V36A1,1,0,0,0,44,35Z"
                                />
                            </g>
                            <g className="mix-blend-multiply">
                                <path
                                    className="secondary"
                                    d="M34,41H30a1,1,0,0,0-1,1V58a1,1,0,0,0,1,1h4a1,1,0,0,0,1-1V42A1,1,0,0,0,34,41Z"
                                />
                            </g>
                        </g>
                    </g>
                </svg>
            </SVGPictogramWrapper>
        );
    }
);

WindowWithBarGraph.displayName = "WindowWithBarGraph";

export default WindowWithBarGraph;
