// prettier-ignore
export const PictogramsNames = {
    AA                              : "AA" ,
    BOU                             : "BOU" ,
    ArrowsOverlapping               : "ArrowsOverlapping" ,
    BadgeWithRibbon                 : "BadgeWithRibbon" ,
    BadgeWithTick                   : "BadgeWithTick",
    BankWithPerson                  : "BankWithPerson" ,
    BankWithShield                  : "BankWithShield" ,
    BarsWithExcalamationMark        : "BarsWithExcalamationMark",
    Bank                            : "Bank" ,
    Banking                         : "Banking" ,
    BankWithBraces                  : "BankWithBraces" ,
    BankWithExclamation             : "BankWithExclamation",
    BankWithCoin                    : "BankWithCoin",
    BankWithCross                   : "BankWithCross",
    BankWithMagnifyingGlassAndStars : "BankWithMagnifyingGlassAndStars",
    BeerMug                         : "BeerMug" ,
    BillWithTax                     : "BillWithTax",
    Bird                            : "Bird" ,
    BookWithKarmaSymbol             : "BookWithKarmaSymbol" ,
    Book                            : "Book" ,
    BoxWithBraces                   : "BoxWithBraces",
    BoxWithCash                     : "BoxWithCash",
    BoxWithCoin                     : "BoxWithCoin",
    BoxWithMobile                   : "BoxWithMobile" ,
    BoxWithShapes                   : "BoxWithShapes" ,
    BoxWithStar                     : "BoxWithStar" ,
    BoxWithLeftArrow                : "BoxWithLeftArrow",
    BoxWithRightArrow               : "BoxWithRightArrow",
    BSA                             : "BSA",
    Brain                           : "Brain" ,
    Briefcase                       : "Briefcase" ,
    BuildingPictogram               : "BuildingPictogram" ,
    Buildings                       : "Buildings" ,
    BuildingWithFlagPictogram       : "BuildingWithFlagPictogram",
    Bulb                            : "Bulb" ,
    COU                             : "COU" ,
    CableTV                         : "CableTV",
    CarPictogram                    : "CarPictogram",
    Clock                           : "Clock" ,
    Calendar                        : "Calendar" ,
    CalloutsWithMultipleScripts     : "CalloutsWithMultipleScripts",
    CashWithUpArrow                 : "CashWithUpArrow" ,
    Cash                            : "Cash" ,
    Cat                             : "Cat" ,
    ChatBot                     : "ChatBot",
    ChatBubbles                     : "ChatBubbles",
    Checklist                       : "Checklist" ,
    Chord                           : "Chord" ,
    CircleWithCross                 : "CircleWithCross",
    CircleWithPlus                  : "CircleWithPlus",
    CircleWithStarAndLines          : "CircleWithStarAndLines" ,
    CircleWithTick                  : "CircleWithTick",
    CoinWithDownArrow               : "CoinWithDownArrow" ,
    Courage                         : "Courage" ,
    Craftsmanship                   : "Craftsmanship" ,
    CreditCardPictogram             : "CreditCardPictogram",
    CylinderPictogram               : "CylinderPictogram",
    Data                            : "Data" ,
    Deposits                        : "Deposits" ,
    DocumentWithArrow               : "DocumentWithArrow",
    DocumentWithBadgeAndTick        : "DocumentWithBadgeAndTick" ,
    DocumentWithCommas              : "DocumentWithCommas" ,
    DocumentWithCode                : "DocumentWithCode",
    DocumentWithCoin                : "DocumentWithCoin" ,
    DocumentWithDetails             : "DocumentWithDetails" ,
    DocumentWithGreenTick           : "DocumentWithGreenTick" ,
    DocumentWithKey                 : "DocumentWithKey" ,
    DocumentWithLock                : "DocumentWithLock" ,
    DocumentWithRedBadge            : "DocumentWithRedBadge" ,
    DownArrowWithCoin               : "DownArrowWithCoin" ,
    Droplets                        : "Droplets",
    Empathy                         : "Empathy" ,
    Envelope                        : "Envelope" ,
    eSign                           : "eSign" ,
    Fastag                          : "Fastag" ,
    Flag                            : "Flag" ,
    FlaskWithBraces                 : "FlaskWithBraces",
    FlaskWithCode                   : "FlaskWithCode",
    FolderWithMagnifyingGlass       : "FolderWithMagnifyingGlass",
    FolderWithArrowsAndPaper        : "FolderWithArrowsAndPaper" ,
    FolderWithArrows                : "FolderWithArrows" ,
    FolderWithShield                : "FolderWithShield" ,
    FunnelWithPlusSymbol            : "FunnelWithPlusSymbol" ,
    GasPipe                         : "GasPipe",
    GraphBar                        : "GraphBar" ,
    Groceries                       : "Groceries",
    GrowthMindset                   : "GrowthMindset" ,
    GuyFawkesMask                   : "GuyFawkesMask" ,
    Hat                             : "Hat",
    Headphones                      : "Headphones" ,
    HeartWithCross                  : "HeartWithCross",
    HomeWithBraces                  : "HomeWithBraces",
    Hourglass                       : "Hourglass" ,
    IdCard                          : "IdCard" ,
    KYC                             : "KYC" ,
    Integrity                       : "Integrity" ,
    Jigsaw                          : "Jigsaw" ,
    LandlinePictogram               : "LandlinePictogram",
    Lending                         : "Lending" ,
    Link                            : "Link" ,
    Lock                            : "Lock" ,
    MagnifyingGlassWithRupee        : "MagnifyingGlassWithRupee",
    Map                             : "Map" ,
    Medal                           : "Medal",
    MessageCallout                  : "MessageCallout" ,
    Metro                           : "Metro",
    Mic                             : "Mic" ,
    MobilePlainWithCoin             : "MobilePlainWithCoin" ,
    MobileWithAsync                 : "MobileWithAsync" ,
    MobileWithCash                  : "MobileWithCash" ,
    MobileWithCircularArrows        : "MobileWithCircularArrows" ,
    MobileWithCoin                  : "MobileWithCoin" ,
    MobileWithCursor                : "MobileWithCursor" ,
    MobileWithGreenTick             : "MobileWithGreenTick" ,
    MobileWithLightning             : "MobileWithLightning",
    MobileWithNotification          : "MobileWithNotification" ,
    MobileWithOffer                 : "MobileWithOffer" ,
    MobileWithRupee                 : "MobileWithRupee",
    MobileWithTag                   : "MobileWithTag" ,
    MobileWithUpi                   : "MobileWithUpi" ,
    MobilityCard : "MobilityCard",
    ModemPictogram                  : "ModemPictogram",
    Newspaper                       : "Newspaper" ,
    Note                            : "Note" ,
    Notepad                         : "Notepad" ,
    Necklace                         : "Necklace" ,
    ONDC                            : "ONDC" ,
    OpenBoxWithBraces               : "OpenBoxWithBraces",
    PaintRoller                     : "PaintRoller" ,
    PanWithExclamation                  : "PanWithExclamation",
    PaperWithCoin                   : "PaperWithCoin",
    Parchment                       : "Parchment" ,
    Payments                        : "Payments" ,
    People                          : "People",
    PeopleWithCoin                  : "PeopleWithCoin" ,
    PeopleWithColouredHeads         : "PeopleWithColouredHeads" ,
    PeopleWithLeader                : "PeopleWithLeader" ,
    PersonWithCircularBackground    : "PersonWithCircularBackground" ,
    PersonWithCoin                  : "PersonWithCoin" ,
    PersonCardWithSettings          : "PersonCardWithSettings" ,
    PersonScan                      : "PersonScan" ,
    PersonWithCape                  : "PersonWithCape" ,
    PersonWithCard                  : "PersonWithCard" ,
    PersonWithGear                  : "PersonWithGear",
    PersonWithHeart                 : "PersonWithHeart" ,
    PersonWithMagnifyingGlass       : "PersonWithMagnifyingGlass" ,
    PersonWithPuzzlePiece           : "PersonWithPuzzlePiece" ,
    PersonWithSettings              : "PersonWithSettings" ,
    PersonWithTools                 : "PersonWithTools",
    PersonWithQuestionMark                 : "PersonWithQuestionMark",
    Person                          : "Person" ,
    PlantWithLeaves                 : "PlantWithLeaves" ,
    Plant                           : "Plant" ,
    Receipt                         : "Receipt" ,
    ReceiptWithBell                 : "ReceiptWithBell" ,
    ReceiptWithCoin                 : "ReceiptWithCoin" ,
    RingWithDiamond                 : "RingWithDiamond",
    Rocket                          : "Rocket" ,
    ScreenWithPlayButton            : "ScreenWithPlayButton",
    Servers                         : "Servers" ,
    ShieldWithTickPictogram         : "ShieldWithTickPictogram",
    Shield                          : "Shield" ,
    ShoppingBags                    : "ShoppingBags",
    Signpost                        : "Signpost" ,
    SIM                             : "SIM",
    StampWithTick                   : "StampWithTick" ,
    Stopwatch                       : "Stopwatch" ,
    SunsetWithCoin                  : "SunsetWithCoin",
    TabletWithPen                   : "TabletWithPen" ,
    Team                            : "Team" ,
    Tenacity                        : "Tenacity" ,
    ThoughtCloud                    : "ThoughtCloud" ,
    Ticket                          : "Ticket" ,
    Tools                           : "Tools" ,
    Transactions                    : "Transactions" ,
    TV                              : "TV",
    UmbrellaWithCoinAndCash         : "UmbrellaWithCoinAndCash",
    UPI                             : "UPI" ,
    Wave                            : "Wave" ,
    WebSettings                     : "WebSettings" ,
    Window                          : "Window" ,
    WindowEmpty                     : "WindowEmpty" ,
    WrenchAndScrewDriver            : "WrenchAndScrewDriver",
    WindowPlainWithPlant            : "WindowPlainWithPlant" ,
    WindowWithBarGraph              : "WindowWithBarGraph" ,
    WindowWithBlocks                : "WindowWithBlocks",
    WindowWithBraces                : "WindowWithBraces" ,
    WindowWithBugAndMagnifyingGlass : "WindowWithBugAndMagnifyingGlass" ,
    WindowWithBracesAndCog          : "WindowWithBracesAndCog" ,
    WindowWithCodeAndBraces         : "WindowWithCodeAndBraces" ,
    WindowWithGreenTick             : "WindowWithGreenTick" ,
    WindowWithInfinity              : "WindowWithInfinity" ,
    WindowWithLightning             : "WindowWithLightning" ,
    WindowWithMagnifyingGlass       : "WindowWithMagnifyingGlass" ,
    WindowWithMobile                : "WindowWithMobile" ,
    WindowWithPlayButton            : "WindowWithPlayButton" ,
    WindowWithSettings              : "WindowWithSettings" ,
    WindowWithUpArrow               : "WindowWithUpArrow" ,
} as const;
